import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {LocalDatabase} from '../local-db';
import {CloudGame,CloudError} from '../game';
import {api} from '../api';
import {bank} from '../../server/content';
test('cloud rejections retain the original timer and allow a typo-corrected retry or timeout',async()=>{
 const {db,game,advance}=await setup();try{
 const rid=await game.createRun('alice',{}),first=await game.begin(rid,'alice');advance();
 for(let i=0;i<5;i++){const rejected=await game.submit(rid,'alice',{index:0,answer:'zzzzzzzzzz',requestId:'rejected-'+i});assert.ok(rejected.feedback);assert.equal(rejected.outcome,undefined);assert.equal(rejected.deadline,first.deadline);assert.equal(rejected.total,0);assert.equal(rejected.answered,0);assert.equal((await game.begin(rid,'alice')).round,0);}
 await game.report('alice',{runId:rid,index:0,answer:'zzzzzzzzzz',explanation:'Review this'});assert.equal((await db.prepare('SELECT * FROM cloud_reports').all()).results.length,1);assert.equal((await game.state(rid,'alice')).answered,0);
 const answer=bank.find(p=>p.id===first.prompt!.id)!.answers.find(a=>a.canonical.length>5)!.canonical;
 const suggested=await game.submit(rid,'alice',{index:0,answer:answer+'z',requestId:'typo-answer'});assert.equal(suggested.suggestion?.canonical,answer);assert.equal(suggested.answered,0);assert.equal(suggested.deadline,first.deadline);const accepted=await game.submit(rid,'alice',{index:0,answer:answer+'z',confirmAnswer:answer,requestId:'confirmed-typo'});assert.equal(accepted.outcome?.canonical,answer);assert.equal(accepted.answered,1);
 const second=await game.begin(rid,'alice');advance();const secondAnswer=bank.find(p=>p.id===second.prompt!.id)!.answers.find(a=>a.canonical.length>5)!.canonical;assert.ok((await game.submit(rid,'alice',{index:1,answer:secondAnswer+'z',requestId:'second-suggest'})).suggestion);advance(26000);assert.equal((await game.submit(rid,'alice',{index:1,answer:secondAnswer+'z',confirmAnswer:secondAnswer,requestId:'late-confirmation'})).outcome?.status,'timeout');
 const practice=await game.createRun('alice',{relaxed:true});await game.begin(practice,'alice');advance(999999);assert.ok((await game.submit(practice,'alice',{index:0,answer:'zzzzzzzzzz',requestId:'practice-retry'})).feedback);assert.equal((await game.state(practice,'alice')).state,'answering');
 }finally{db.db.close();}
});

test('lossless snapshot compression keeps long Endless documents below the D1 row limit and reads old saves',async()=>{const {db,game}=await setup();try{const run=game.makeRun('alice','endless',false,game.categories(undefined));run.snapshot=Array.from({length:1200},(_,index)=>bank[index%bank.length]);assert.ok(Buffer.byteLength(JSON.stringify(run))>2_000_000);const packed=await game.packRun(run);assert.ok(Buffer.byteLength(packed)<2_000_000);assert.deepEqual((await game.unpackRun(packed)).snapshot,run.snapshot);assert.deepEqual((await game.unpackRun(JSON.stringify(run))).snapshot,run.snapshot);}finally{db.db.close();}});

async function setup(path=':memory:') {const db=new LocalDatabase(path);for(const sid of ['alice','bob','eve'])await db.prepare('INSERT OR IGNORE INTO cloud_sessions VALUES(?,?,?)').bind(sid,'csrf-'+sid,1).run();let now=100000;const game=new CloudGame(db,bank,()=>now);return {db,game,advance:(ms=3100)=>{now+=ms;}};}
async function seven(game:CloudGame,rid:string,sid:string,advance:()=>void){const prompts:string[]=[];for(let index=0;index<7;index++){const view=await game.begin(rid,sid);prompts.push(view.prompt!.id);advance();const prompt=bank.find(p=>p.id===view.prompt!.id)!;await game.submit(rid,sid,{index,answer:prompt.answers.find(a=>a.tier==='gem')!.canonical,requestId:'request-'+index});}return prompts;}

test('cloud adapter preserves scoring, immutable challenge snapshots, privacy and slot claiming',async()=>{const {db,game,advance}=await setup();try{const cid=await game.createChallenge('alice',{nickname:'Alice'});const invitation=await game.summary(cid,'bob');assert.equal(invitation.results,undefined);assert.equal(invitation.snapshot,undefined);const creatorId=invitation.players.length===1?(await game.summary(cid,'alice')).runId:null;const friendId=await game.claim(cid,'bob','Bob');await assert.rejects(game.claim(cid,'eve','Eve'),(e:unknown)=>e instanceof CloudError&&e.status===409);const first=await seven(game,creatorId,'alice',advance);const changed=structuredClone(bank);for(const p of changed)p.answers=p.answers.map(a=>({...a,canonical:'new-content-'+a.id}));const updatedGame=new CloudGame(db,changed,game.clock,1,1);const hidden=await updatedGame.summary(cid,'bob');assert.equal(hidden.results,undefined);const second=await seven(updatedGame,friendId,'bob',advance);assert.deepEqual(second,first);const comparison=await game.summary(cid,'bob');assert.deepEqual(comparison.results.map((r:any)=>r.total),[700,700]);assert.equal((await game.summary(cid,'eve')).results,undefined);}finally{db.db.close();}});

test('cloud version guards handle concurrent begin, submit, challenge creation and guest claims',async()=>{const {db,game,advance}=await setup();try{const rid=await game.createRun('alice',{});const beginnings=await Promise.all(Array.from({length:5},()=>game.begin(rid,'alice')));assert.equal(new Set(beginnings.map(r=>r.round)).size,1);assert.equal(new Set(beginnings.map(r=>r.prompt!.id)).size,1);advance();const prompt=bank.find(p=>p.id===beginnings[0].prompt!.id)!;const body={index:0,answer:prompt.answers.find(a=>a.tier==='gem')!.canonical,requestId:'concurrent-one'};const submitted=await Promise.all([game.submit(rid,'alice',body),game.submit(rid,'alice',{...body,answer:'wrong',requestId:'concurrent-two'})]);assert.equal(submitted[0].total,100);assert.ok(submitted[1].feedback||submitted[1].total===100);assert.equal((await game.state(rid,'alice')).answered,1);const cid=await game.createChallenge('alice',{});const claims=await Promise.allSettled([game.claim(cid,'bob','Bob'),game.claim(cid,'eve','Eve')]);assert.equal(claims.filter(r=>r.status==='fulfilled').length,1);assert.equal((await game.summary(cid,'alice')).players.length,2);const complete=await game.createRun('alice',{});await seven(game,complete,'alice',advance);const challenges=await Promise.all([game.createChallenge('alice',{runId:complete}),game.createChallenge('alice',{runId:complete})]);assert.equal(challenges[0],challenges[1]);}finally{db.db.close();}});

test('cloud Endless, deadlines, retries and database reopen retain authoritative results',async()=>{const directory=mkdtempSync(join(tmpdir(),'deep-cloud-'));const path=join(directory,'persist.sqlite');let db:LocalDatabase|undefined;try{const setupResult=await setup(path);db=setupResult.db;const {game,advance}=setupResult;const rid=await game.createRun('alice',{mode:'endless'});for(let index=0;index<57;index++){const reading=await game.begin(rid,'alice');advance();const prompt=bank.find(p=>p.id===reading.prompt!.id)!;const body={index,answer:prompt.answers.find(a=>a.tier==='gem')!.canonical,requestId:'endless-'+index};await game.submit(rid,'alice',body);assert.equal((await game.submit(rid,'alice',body)).total,(index+1)*100);}const finished=await game.endEndless(rid,'alice');assert.equal(finished.total,5700);assert.equal(finished.stageDepth,1000);const timed=await game.createRun('alice',{});await game.begin(timed,'alice');await assert.rejects(game.submit(timed,'alice',{index:0,answer:'x',requestId:'too-early'}));advance(28251);assert.equal((await game.state(timed,'alice')).outcome!.status,'timeout');db.db.close();db=new LocalDatabase(path);const reloaded=new CloudGame(db,bank);assert.equal((await reloaded.state(rid,'alice')).total,5700);}finally{db?.db.close();rmSync(directory,{recursive:true,force:true});}});

test('cloud fetch API enforces session/CSRF, handles errors and never returns the answer bank',async()=>{const db=new LocalDatabase();try{const initial=await api(new Request('https://game.test/api/session'),{DB:db});const info=await initial.json() as any;const cookie=initial.headers.get('set-cookie')!.split(';')[0];assert.equal(info.content.prompts,bank.filter(p=>p.reviewed).length);assert.equal(info.bank,undefined);const denied=await api(new Request('https://game.test/api/runs',{method:'POST',headers:{cookie},body:'{}'}),{DB:db});assert.equal(denied.status,403);const headers={cookie,origin:'https://game.test','x-csrf-token':info.csrf};const created=await api(new Request('https://game.test/api/runs',{method:'POST',headers,body:'{}'}),{DB:db});assert.equal(created.status,200);const rid=(await created.json() as any).runId;const stranger=await api(new Request('https://game.test/api/runs/'+rid),{DB:db});assert.equal(stranger.status,404);const malformed=await api(new Request('https://game.test/api/runs',{method:'POST',headers,body:'{'}),{DB:db});assert.equal(malformed.status,400);}finally{db.db.close();}});
