import {matchAnswer, suggestAnswer, selectPrompts, phase, eligiblePrompts, parseDifficulty, parseTopics} from '../src/shared/core';
import {CATEGORIES, POINTS, SCORING_VERSION, type DifficultyMode, type Prompt, type Category, type Outcome, type RunView} from '../src/shared/types';

export interface Statement {
  bind(...values: unknown[]): Statement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<{results: T[]}>;
  run(): Promise<{meta: {changes: number}}>;
}
export interface Database { prepare(sql: string): Statement; batch(statements: Statement[]): Promise<{meta: {changes: number}}[]> }
export class CloudError extends Error { constructor(public status: number, message: string) { super(message); } }
export const newId = () => { const bytes = crypto.getRandomValues(new Uint8Array(24)); return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); };
type Rules = {readingMs: number; answerMs: number; toleranceMs: number; difficulty?:DifficultyMode; topics?:Category[]; scoringVersion?:string; points: typeof POINTS};
type Round = {start: number; readingUntil: number; deadline: number | null; requestId?: string; outcome?: Outcome};
type Run = {id: string; session: string; mode: 'solo' | 'endless' | 'challenge'; relaxed: boolean; snapshot: Prompt[]; categories: Category[]; recent: string[]; cycled: boolean; complete: boolean; created: number; rounds: Round[]; rules: Rules; challengeId?: string};
type Player = {session: string; nickname: string; runId: string};
type Challenge = {id: string; created: number; expires: number; rules: Rules; snapshot: Prompt[]; creator: Player; friend?: Player};
type Stored<T> = {state: string; version: number};

// Each run/challenge is a persistent document. A version-guarded UPDATE is its
// transaction boundary: simultaneous requests retry against the winning state.
// Creation and friend claiming use atomic D1 batches with guarded INSERTs.
export class CloudGame {
  constructor(public db: Database, public bank: Prompt[], public clock = Date.now, public readingMs = 3000, public answerMs = 25000) {}
  statement(sql: string, ...values: unknown[]) { return this.db.prepare(sql).bind(...values); }
  async packRun(run: Run) { const {snapshot,...state}=run; const compressed=new Uint8Array(await new Response(new Blob([JSON.stringify(snapshot)]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());let binary='';for(let offset=0;offset<compressed.length;offset+=8192)binary+=String.fromCharCode(...compressed.subarray(offset,offset+8192));return JSON.stringify({...state,snapshotGzip:btoa(binary)}); }
  async unpackRun(state: string): Promise<Run> { const parsed=JSON.parse(state);if(parsed.snapshot)return parsed;const compressed=Uint8Array.from(atob(parsed.snapshotGzip),(c:string)=>c.charCodeAt(0));const snapshot=await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'))).json();delete parsed.snapshotGzip;return {...parsed,snapshot} as Run; }
  categories(raw: unknown): Category[] {try{return parseTopics(raw);}catch(e){throw new CloudError(400,(e as Error).message);}}
  difficulty(raw:unknown):DifficultyMode{try{return parseDifficulty(raw);}catch(e){throw new CloudError(400,(e as Error).message);}}
  nickname(value: unknown) { if(value === undefined || value === '') return 'Guest diver'; if(typeof value !== 'string' || value.length > 24 || /[\p{C}]/u.test(value)) throw new CloudError(400,'Use a nickname of 1–24 visible characters.'); return value.trim() || 'Guest diver'; }
  makeRun(session: string, mode: Run['mode'], relaxed: boolean, categories: Category[], recent: string[] = [], snapshot?: Prompt[], rules?: Rules, difficulty:DifficultyMode='easy'): Run {
    let selected; try { selected = snapshot ? {prompts: snapshot, cycled: false} : selectPrompts(eligiblePrompts(this.bank,categories,difficulty),7,recent,Math.random,difficulty); } catch(e) { throw new CloudError(400,(e as Error).message); }
    return {id:newId(),session,mode,relaxed,categories,recent,snapshot:selected.prompts,cycled:selected.cycled,complete:false,created:this.clock(),rounds:[],rules:rules ?? {difficulty,topics:categories,scoringVersion:SCORING_VERSION,readingMs:this.readingMs,answerMs:this.answerMs,toleranceMs:250,points:{...POINTS}}};
  }
  async insertRun(run: Run) { return this.statement('INSERT INTO cloud_runs(id,session_id,state,version,created) VALUES(?,?,?,0,?)',run.id,run.session,await this.packRun(run),run.created); }
  async createRun(session: string, body: any) { if(body.mode !== undefined && !['solo','endless'].includes(body.mode)) throw new CloudError(400,'Unknown dive format.'); const recent = Array.isArray(body.recent) ? body.recent.filter((v:unknown) => typeof v === 'string').slice(-500) : []; const run = this.makeRun(session,body.mode ?? 'solo',body.relaxed === true,this.categories(body.categories),recent,undefined,undefined,this.difficulty(body.difficulty)); await (await this.insertRun(run)).run(); return run.id; }
  async challenge(cid: string): Promise<Challenge> { const row = await this.statement('SELECT state FROM cloud_challenges WHERE id=?',cid).first<{state:string}>(); if(!row) throw new CloudError(404,'We couldn’t find this challenge. Check the link or start a new dive.'); const c: Challenge = JSON.parse(row.state); if(c.expires < this.clock()) throw new CloudError(410,'This challenge has expired after 30 days. Start a fresh challenge.'); return c; }
  async storedRun(rid: string, session: string) { const stored = await this.statement('SELECT state,version FROM cloud_runs WHERE id=? AND session_id=?',rid,session).first<Stored<Run>>(); if(!stored) throw new CloudError(404,'This dive belongs to another browser, or no longer exists. Start a new dive.'); const run = await this.unpackRun(stored.state); if(run.challengeId) await this.challenge(run.challengeId); return {stored,run}; }
  async mutate<T>(rid: string, session: string, action: (run: Run) => T): Promise<T> {
    for(let attempt=0;attempt<12;attempt++) { const {stored,run} = await this.storedRun(rid,session); const before = JSON.stringify(run); const result = action(run); if(JSON.stringify(run) === before) return result; const state = await this.packRun(run); const updated = await this.statement('UPDATE cloud_runs SET state=?,version=version+1 WHERE id=? AND version=?',state,rid,stored.version).run(); if(updated.meta.changes === 1) return result; }
    throw new CloudError(503,'Your dive is busy saving another request. Retry to check your progress.');
  }
  commit(run: Run, raw: string, timeout: boolean, requestId: string, confirmed?:string) { const index = run.rounds.length-1; const round = run.rounds[index]; const prompt = run.snapshot[index]; const match = timeout ? null : matchAnswer(prompt,confirmed??raw); round.requestId = requestId; round.outcome = {index,promptId:prompt.id,promptVersion:prompt.version,prompt:prompt.text,submitted:timeout?'':raw,canonical:match?.canonical ?? null,tier:match?.tier ?? null,points:match?run.rules.points[match.tier]:0,status:timeout?'timeout':match?'accepted':'invalid',explanation:timeout?'No answer was committed before the deadline.':match?match.explanation:'We couldn’t match that to this question’s answer list.'}; if(run.mode !== 'endless' && index === 6) run.complete = true; }
  reconcile(run: Run) { const round = run.rounds.at(-1); if(round && !round.outcome && round.deadline !== null && this.clock() > round.deadline + run.rules.toleranceMs) this.commit(run,'',true,'timeout'); }
  view(run: Run): RunView {
    const latest = run.rounds.at(-1); const index = Math.max(0,run.rounds.length-1); const stage = Math.floor(index/7); const outcomes = run.rounds.flatMap(r => r.outcome ? [r.outcome] : []); const total = outcomes.reduce((sum,o) => sum+o.points,0); const stageTotal = outcomes.filter(o => Math.floor(o.index/7) === stage).reduce((sum,o) => sum+o.points,0);
    const view: RunView = {id:run.id,difficulty:run.rules.difficulty??'mixed',topics:run.rules.topics??run.categories,scoringVersion:run.rules.scoringVersion??'editorial-v1',mode:run.mode,relaxed:run.relaxed,state:run.complete?'complete':latest?.outcome?'result':latest?phase(this.clock(),latest.readingUntil,latest.deadline)==='reading'?'reading':'answering':'result',serverNow:this.clock(),readingUntil:latest?.readingUntil ?? null,deadline:latest?.deadline ?? null,round:index,total,depth:total*10,stageDepth:stageTotal*10,stage:stage+1,answered:outcomes.length,cycled:run.cycled,challengeId:run.challengeId};
    if(latest) { const p = run.snapshot[index]; view.prompt = {id:p.id,version:p.version,category:p.category,text:p.text,notes:p.qualificationNotes}; if(latest.outcome) view.outcome = latest.outcome; }
    if(run.complete) view.recap = outcomes.map(o => ({...o,examples:run.snapshot[o.index].answers.filter(a => a.canonical !== o.canonical).slice(0,3).map(a => `${a.canonical} · ${run.rules.points[a.tier]} points`)}));
    return view;
  }
  state(rid: string, session: string) { return this.mutate(rid,session,r => { this.reconcile(r); return this.view(r); }); }
  begin(rid: string, session: string) { return this.mutate(rid,session,r => { if(r.complete) return this.view(r); const previous = r.rounds.at(-1); if(previous && !previous.outcome) { this.reconcile(r); return this.view(r); } const index = r.rounds.length; if(index >= r.snapshot.length) { if(r.mode !== 'endless') { r.complete = true; return this.view(r); } const eligible = eligiblePrompts(this.bank,r.categories,r.rules.difficulty??'mixed'); const recent = [...r.recent,...r.snapshot.map(p => p.id)]; const selected = selectPrompts(eligible,7,recent,Math.random,r.rules.difficulty??'mixed'); r.snapshot.push(...selected.prompts); r.recent = recent.slice(-eligible.length); r.cycled = selected.cycled; } const now = this.clock(); r.rounds.push({start:now,readingUntil:now+r.rules.readingMs,deadline:r.relaxed?null:now+r.rules.readingMs+r.rules.answerMs}); return this.view(r); }); }
  submit(rid: string, session: string, body: any, received = this.clock()) { return this.mutate(rid,session,r => { const round = r.rounds.at(-1); if(!round) throw new CloudError(409,'Start the question first.'); if(!Number.isInteger(body.index) || body.index !== r.rounds.length-1) { const old = r.rounds[body.index]; if(old?.outcome && old.requestId === body.requestId) return this.view(r); throw new CloudError(409,'This answer belongs to a different question. Refresh your dive.'); } if(round.outcome) return this.view(r); if(typeof body.requestId !== 'string' || body.requestId.length < 8 || body.requestId.length > 100) throw new CloudError(400,'A submission reference is required.'); if(typeof body.answer !== 'string' || body.answer.length > 120) throw new CloudError(400,'Answers must be 120 characters or fewer.'); if(received < round.readingUntil) throw new CloudError(409,'The reading period has not finished.'); const timedOut = round.deadline !== null && received > round.deadline+r.rules.toleranceMs; if(body.timeout === true && round.deadline !== null && !timedOut) throw new CloudError(409,'The answer period has not finished.'); if(body.timeout === true && round.deadline === null) throw new CloudError(400,'Practice has no timeout.'); let confirmed:string|undefined;if(!timedOut&&body.timeout!==true&&!matchAnswer(r.snapshot[r.rounds.length-1],body.answer)){const suggestion=suggestAnswer(r.snapshot[r.rounds.length-1],body.answer);if(suggestion&&body.confirmAnswer===suggestion.canonical)confirmed=suggestion.canonical;else if(suggestion)return {...this.view(r),suggestion:{canonical:suggestion.canonical,submitted:body.answer}};else return {...this.view(r),feedback:'That answer is not in the accepted list. Try another answer; the timer keeps running.'};}this.commit(r,body.answer,timedOut || body.timeout === true,body.requestId,confirmed); return this.view(r); }); }
  endEndless(rid: string, session: string) { return this.mutate(rid,session,r => { if(r.mode !== 'endless') throw new CloudError(400,'Only Endless dives can finish early.'); this.reconcile(r); if(r.rounds.at(-1) && !r.rounds.at(-1)!.outcome) throw new CloudError(409,'Finish the active question before ending the dive.'); r.complete = true; return this.view(r); }); }
  async createChallenge(session: string, body: any): Promise<string> {
    const nickname = this.nickname(body.nickname);
    for(let attempt=0;attempt<12;attempt++) {
      const source = body.runId ? await this.storedRun(body.runId,session) : null;
      if(source && (!source.run.complete || source.run.mode !== 'solo' || source.run.relaxed)) throw new CloudError(400,'Only a completed timed seven-question solo dive can be shared as a challenge.');
      if(source?.run.challengeId) return source.run.challengeId;
      const run = source?.run ?? this.makeRun(session,'challenge',false,this.categories(body.categories),[],undefined,undefined,this.difficulty(body.difficulty)); const cid = newId(); const now = this.clock(); run.challengeId = cid;
      const c: Challenge = {id:cid,created:now,expires:now+30*86400000,rules:run.rules,snapshot:run.snapshot,creator:{session,nickname,runId:run.id}};
      if(!source) { await this.db.batch([await this.insertRun(run),this.statement('INSERT INTO cloud_challenges(id,creator_run_id,state,version,created,expires) VALUES(?,?,?,0,?,?)',cid,run.id,JSON.stringify(c),now,c.expires)]); return cid; }
      const result = await this.db.batch([this.statement('UPDATE cloud_runs SET state=?,version=version+1 WHERE id=? AND version=?',await this.packRun(run),run.id,source.stored.version),this.statement("INSERT INTO cloud_challenges(id,creator_run_id,state,version,created,expires) SELECT ?,?,?,0,?,? WHERE EXISTS(SELECT 1 FROM cloud_runs WHERE id=? AND version=? AND json_extract(state,'$.challengeId')=?)",cid,run.id,JSON.stringify(c),now,c.expires,run.id,source.stored.version+1,cid)]);
      if(result[0].meta.changes === 1) return cid;
    }
    throw new CloudError(503,'Your challenge is busy saving. Retry to check it.');
  }
  async claim(cid: string, session: string, rawName: unknown): Promise<string> {
    for(let attempt=0;attempt<12;attempt++) { const c = await this.challenge(cid); if(c.creator.session === session) return c.creator.runId; if(c.friend?.session === session) return c.friend.runId; if(c.friend) throw new CloudError(409,'This challenge already has two players. Start a separate game.'); const stored = await this.statement('SELECT state,version FROM cloud_challenges WHERE id=?',cid).first<Stored<Challenge>>(); if(!stored) continue; const fresh: Challenge = JSON.parse(stored.state); if(fresh.friend) continue; const run = this.makeRun(session,'challenge',false,fresh.rules.topics??[...new Set(fresh.snapshot.map(p=>p.category))],[],fresh.snapshot,fresh.rules); run.challengeId = cid; fresh.friend = {session,nickname:this.nickname(rawName),runId:run.id}; const result = await this.db.batch([this.statement('UPDATE cloud_challenges SET state=?,version=version+1 WHERE id=? AND version=?',JSON.stringify(fresh),cid,stored.version),this.statement("INSERT INTO cloud_runs(id,session_id,state,version,created) SELECT ?,?,?,0,? WHERE EXISTS(SELECT 1 FROM cloud_challenges WHERE id=? AND version=? AND json_extract(state,'$.friend.runId')=?)",run.id,session,await this.packRun(run),run.created,cid,stored.version+1,run.id)]); if(result[0].meta.changes === 1) return run.id; }
    throw new CloudError(503,'The challenge is busy saving another guest. Retry to check your place.');
  }
  async summary(cid: string, session: string) { const c = await this.challenge(cid); const players = [{...c.creator,role:'creator'},...(c.friend?[{...c.friend,role:'friend'}]:[])]; const own = players.find(p => p.session === session); const states = await Promise.all(players.map(p => this.state(p.runId,p.session))); const result: any = {id:cid,creator:c.creator.nickname,expires:c.expires,rules:c.rules,players:players.map((p,i) => ({role:p.role,nickname:p.nickname,complete:states[i].state === 'complete'})),full:players.length===2,ownRole:own?.role,runId:own?.runId}; if(own && states[players.indexOf(own)].state === 'complete') result.results = players.map((p,i) => states[i].state === 'complete'?{nickname:p.nickname,role:p.role,total:states[i].total,depth:states[i].depth,recap:states[i].recap}:{nickname:p.nickname,role:p.role,pending:true}); return result; }
  async rematch(cid: string, session: string, nickname: unknown) { const c = await this.challenge(cid); if(c.creator.session !== session && c.friend?.session !== session) throw new CloudError(403,'Only a participant can create this rematch.'); return this.createChallenge(session,{nickname}); }
  async report(session: string, body: any) { if(typeof body.runId !== 'string' || !Number.isInteger(body.index)) throw new CloudError(400,'A completed question is required.'); const {run} = await this.storedRun(body.runId,session); const round=run.rounds[body.index],prompt=run.snapshot[body.index];const rejected=round&&prompt&&typeof body.answer==='string'&&body.answer.trim()&&body.answer.length<=120&&!matchAnswer(prompt,body.answer);if(!round?.outcome&&!rejected)throw new CloudError(400,'Submit an unmatched answer first.');const o=round.outcome??{promptId:prompt.id,promptVersion:prompt.version,submitted:body.answer}; const explanation = typeof body.explanation === 'string'?body.explanation.trim():''; if(explanation.length>1000) throw new CloudError(400,'Keep the explanation under 1,000 characters.'); await this.statement('INSERT INTO cloud_reports(id,session_id,prompt_id,prompt_version,submitted,explanation,created) VALUES(?,?,?,?,?,?,?)',newId(),session,o.promptId,o.promptVersion,o.submitted,explanation,this.clock()).run(); }
}
