import {test,expect,type Page} from '@playwright/test';
import {bank} from '../../server/content';

test('Easy defaults, multiple topics, persisted settings, balanced fresh runs and Hard challenges',async({page,browser})=>{
 await page.goto('/');await page.locator('.dive-options summary').click();await expect(page.getByLabel('Difficulty',{exact:true})).toHaveValue('easy');await expect(page.getByLabel('All topics',{exact:true})).toBeChecked();
 await page.getByLabel('All topics',{exact:true}).uncheck();await page.getByLabel('Food',{exact:true}).check();await page.getByLabel('Pets',{exact:true}).check();await page.reload();await page.locator('.dive-options summary').click();await expect(page.getByLabel('Food',{exact:true})).toBeChecked();await expect(page.getByLabel('Pets',{exact:true})).toBeChecked();await expect(page.getByLabel('Animals',{exact:true})).not.toBeChecked();
 await page.getByRole('button',{name:'Play unlimited',exact:false}).click();await page.getByRole('button',{name:'Let’s dive',exact:true}).click();const first=await seven(page);const records=first.map(text=>bank.find(p=>p.text===text)!);expect(records.every(p=>p.difficulty==='easy'&&['Food','Pets'].includes(p.category))).toBe(true);expect(records.filter(p=>p.category==='Food').length).toBeGreaterThanOrEqual(3);expect(records.filter(p=>p.category==='Pets').length).toBeGreaterThanOrEqual(3);
 await page.getByRole('button',{name:'Play again',exact:true}).click();const second=await seven(page);expect(new Set([...first,...second]).size).toBe(14);
 await page.goto('/');await page.locator('.dive-options summary').click();await page.getByLabel('All topics',{exact:true}).check();await page.getByLabel('All topics',{exact:true}).uncheck();await page.getByLabel('Science',{exact:true}).check();await page.getByLabel('Difficulty',{exact:true}).selectOption('hard');await page.getByRole('button',{name:'Challenge a friend',exact:false}).click();await page.getByLabel('Your nickname').fill('Hard player');await page.getByRole('button',{name:'Create challenge',exact:true}).click();await expect(page.locator('.challenge-rules')).toContainText('HARD');const url=page.url();await page.getByRole('button',{name:'Play / resume challenge'}).click();const question=await page.locator('.question-panel h2').innerText();expect(bank.find(p=>p.text===question)?.difficulty).toBe('hard');expect(bank.find(p=>p.text===question)?.category).toBe('Science');
 const friend=await browser.newContext({baseURL:'http://localhost:3100'});const other=await friend.newPage();await other.goto(url);await expect(other.locator('.challenge-rules')).toContainText('HARD');await other.getByLabel('Your nickname').fill('Friend');await other.getByRole('button',{name:'Play challenge',exact:true}).click();await expect(other.locator('.question-panel h2')).toHaveText(question);await friend.close();
});

test('eight selected topics survive reload and unavailable selections explain recovery',async({page})=>{
 await page.goto('/');await page.locator('.dive-options summary').click();await page.getByLabel('All topics',{exact:true}).uncheck();for(const topic of ['Food','Animals','Pets','Geography','Music','Films','TV','Books'])await page.getByLabel(topic,{exact:true}).check();await page.reload();await page.locator('.dive-options summary').click();await expect(page.getByLabel('All topics',{exact:true})).not.toBeChecked();await expect(page.locator('.category-grid input:checked')).toHaveCount(8);
 await page.getByLabel('All topics',{exact:true}).check();await page.getByLabel('All topics',{exact:true}).uncheck();await page.getByLabel('TV',{exact:true}).check();await page.getByLabel('Difficulty',{exact:true}).selectOption('hard');await page.getByRole('button',{name:'Play unlimited',exact:false}).click();await page.getByRole('button',{name:'Let’s dive',exact:true}).click();await expect(page.getByRole('alert')).toContainText('seven distinct questions');
});
test('unaccepted answers show feedback and permit a typo retry within the same timer',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Play unlimited',exact:false}).click();await page.getByRole('button',{name:'Let’s dive',exact:true}).click();
 const input=page.getByLabel('Your answer',{exact:true});await expect(input).toBeEnabled();const question=await page.locator('.question-panel h2').innerText();
 await input.fill('zzzzzzzzzz');const rejectedResponse=page.waitForResponse(r=>r.url().endsWith('/submit'));await input.press('Enter');const rejected=await(await rejectedResponse).json();
 await expect(page.getByRole('status').filter({hasText:'not in the accepted list'})).toBeVisible();await expect(input).toBeEnabled();await expect(page.locator('.question-panel h2')).toHaveText(question);expect(rejected.answered).toBe(0);expect(await page.evaluate(()=>localStorage.getItem('deep:pending'))).toBeNull();
 const answer=bank.find(p=>p.text===question)!.answers.find(a=>a.canonical.length>5)!.canonical;await input.fill(answer+'z');const suggestionResponse=page.waitForResponse(r=>r.url().endsWith('/submit'));await input.press('Enter');const suggested=await(await suggestionResponse).json();expect(suggested.answered).toBe(0);expect(suggested.deadline).toBe(rejected.deadline);await expect(page.getByRole('status').filter({hasText:'Did you mean'})).toContainText(answer);await page.getByRole('button',{name:'Dismiss suggestion'}).click();await expect(input).toBeEnabled();await input.press('Enter');await expect(page.getByRole('button',{name:'Yes, that’s my answer'})).toBeVisible();const acceptedResponse=page.waitForResponse(r=>r.url().endsWith('/submit'));await page.getByRole('button',{name:'Yes, that’s my answer'}).click();const accepted=await(await acceptedResponse).json();expect(accepted.deadline).toBe(rejected.deadline);expect(accepted.outcome.canonical).toBe(answer);await expect(page.locator('.round-result')).toBeVisible();
});
async function answerRound(page:Page,answer?:string){const input=page.getByLabel('Your answer',{exact:true});await expect(input).toBeEnabled();const text=await page.locator('.question-panel h2').innerText();const prompt=bank.find(p=>p.text===text)!;await input.fill(answer??prompt.answers.find(a=>a.tier==='gem')!.canonical);await input.press('Enter');await expect(page.locator('.round-result,.recap')).toBeVisible();return text;}
async function seven(page:Page){const prompts:string[]=[];for(let i=0;i<7;i++){prompts.push(await answerRound(page));if(i<6)await page.getByRole('button',{name:'Next prompt',exact:true}).click();}return prompts;}
test('two isolated browsers finish the same pinned challenge, hide spoilers and compare real results',async({browser})=>{const alice=await browser.newContext({baseURL:'http://localhost:3100'});const bob=await browser.newContext({baseURL:'http://localhost:3100'});const a=await alice.newPage();const b=await bob.newPage();await a.goto('/');expect((await alice.request.get('/server/content.ts')).status()).toBe(404);expect((await alice.request.get('/data/deep-trivia.sqlite')).status()).toBe(404);await a.getByRole('button',{name:'Challenge a friend',exact:false}).click();await a.getByLabel('Your nickname').fill('Alice');await a.getByRole('button',{name:'Create challenge',exact:true}).click();await expect(a.getByRole('heading',{name:'Alice’s dive'})).toBeVisible();const url=a.url();await a.getByRole('button',{name:'Play / resume challenge'}).click();const creatorPrompts=await seven(a);await expect(a.locator('.recap-score')).toContainText('700');await expect(a.locator('.recap-score')).toContainText('7,000 m');await a.getByRole('button',{name:'Compare results'}).click();await expect(a.getByRole('heading',{name:'Waiting for your friend'})).toBeVisible();await b.goto(url);await expect(b.getByRole('heading',{name:'Alice’s dive'})).toBeVisible();const summary=await(await bob.request.get(url.replace('/challenge/','/api/challenges/'))).json();expect(summary.results).toBeUndefined();expect(summary.snapshot).toBeUndefined();await b.getByLabel('Your nickname').fill('Bob');await b.getByRole('button',{name:'Play challenge',exact:true}).click();const firstText=await b.locator('.question-panel h2').innerText();await b.reload();await b.getByRole('button',{name:'Resume your saved dive'}).click();await expect(b.locator('.question-panel h2')).toHaveText(firstText);const friendPrompts=await seven(b);expect(friendPrompts).toEqual(creatorPrompts);await b.getByRole('button',{name:'Compare results'}).click();await expect(b.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();await expect(b.locator('.comparison-rounds>div')).toHaveCount(7);await a.getByRole('button',{name:'Refresh results'}).click();await expect(a.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();await b.reload();await expect(b.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();const third=await browser.newContext({baseURL:'http://localhost:3100'});const c=await third.newPage();await c.goto(url);await expect(c.getByRole('heading',{name:'This challenge already has two players.'})).toBeVisible();await third.close();await alice.close();await bob.close();});
test('360px keyboard flow, reduced motion, seven questions, play again and screenshots',async({page})=>{await page.setViewportSize({width:360,height:800});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.screenshot({path:'test-results/mobile-home.png',fullPage:true});await page.getByRole('button',{name:'Play unlimited',exact:false}).click();if(await page.getByRole('button',{name:'Let’s dive',exact:true}).isVisible())await page.getByRole('button',{name:'Let’s dive',exact:true}).click();await expect(page.getByLabel('Your answer',{exact:true})).toBeEnabled();await page.screenshot({path:'test-results/mobile-round.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const animation=await page.locator('.diver').evaluate(el=>getComputedStyle(el).animationName);expect(animation).toBe('none');await page.setViewportSize({width:360,height:460});await page.getByLabel('Your answer',{exact:true}).focus();await page.getByRole('button',{name:'Submit answer'}).scrollIntoViewIfNeeded();const box=await page.getByRole('button',{name:'Submit answer'}).boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual(360);expect(box!.y+box!.height).toBeLessThanOrEqual(460);await seven(page);await page.getByRole('button',{name:'Play again',exact:true}).click();await expect(page.locator('.question-panel h2')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('Endless UI continues after fifty questions and offers an explicit finish',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Endless dive',exact:false}).click();if(await page.getByRole('button',{name:'Let’s dive',exact:true}).isVisible())await page.getByRole('button',{name:'Let’s dive',exact:true}).click();for(let i=0;i<56;i++){await answerRound(page);if(i<55)await page.getByRole('button',{name:i%7===6?'Continue diving':'Next prompt',exact:true}).click();}await expect(page.locator('.endless-stats')).toContainText('56 answered');await expect(page.locator('.endless-stats')).toContainText('56,000 m');await page.getByRole('button',{name:'Continue diving',exact:true}).click();await expect(page.locator('.hud-middle')).toContainText('STAGE 9');await answerRound(page);await page.getByRole('button',{name:'Finish dive',exact:false}).click();await expect(page.locator('.recap')).toBeVisible();await expect(page.locator('.recap-score')).toContainText('5700');});
test('lost response retries the committed request, sharing fallback works and storage/backend failures are explained',async({page,browser})=>{await page.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new Error('denied');}},configurable:true});});await page.goto('/');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'test-results/desktop-home.png',fullPage:true});await page.getByRole('button',{name:'Play unlimited',exact:false}).click();if(await page.getByRole('button',{name:'Let’s dive',exact:true}).isVisible())await page.getByRole('button',{name:'Let’s dive',exact:true}).click();await page.route('**/api/runs/*/submit',async route=>{await route.fetch();await route.abort();await page.unroute('**/api/runs/*/submit');});const text=await page.locator('.question-panel h2').innerText();const gem=bank.find(p=>p.text===text)!.answers.find(a=>a.tier==='gem')!.canonical;const input=page.getByLabel('Your answer',{exact:true});await expect(input).toBeEnabled();await input.fill(gem);await input.press('Enter');await expect(page.getByRole('alert')).toContainText('offline');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.round-result')).toContainText('+100');await page.screenshot({path:'test-results/desktop-result.png',fullPage:true});for(let i=1;i<7;i++){await page.getByRole('button',{name:'Next prompt',exact:true}).click();await answerRound(page);}await page.getByRole('button',{name:'Share result',exact:true}).click();await expect(page.locator('.share-fallback')).toContainText('Select the text below');const message=await page.getByLabel('Sharing text').inputValue();expect(message).toContain('700/700');expect(message).not.toContain(gem);await page.goto('/challenge/not-a-real-link');await expect(page.getByRole('alert')).toContainText('couldn’t find');const context=await browser.newContext({baseURL:'http://localhost:3100'});await context.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('denied');}});});const noStorage=await context.newPage();await noStorage.goto('/');await expect(noStorage.getByRole('status').filter({hasText:'cannot save local'})).toBeVisible();await noStorage.route('**/api/runs',route=>route.abort());await noStorage.getByRole('button',{name:'Play unlimited',exact:false}).click();await noStorage.getByRole('button',{name:'Let’s dive',exact:true}).click();await expect(noStorage.getByRole('alert')).toContainText('offline');await context.close();});
