import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openDatabase} from '../server/database';
import {Game,GameError} from '../server/game';
import {bank} from '../server/content';
import {POINTS} from '../src/shared/types';
function fixture(path=':memory:'){let now=100000;const db=openDatabase(path);const game=new Game(db,structuredClone(bank),()=>now);for(const s of ['creator','friend','third'])if(!game.one('SELECT id FROM sessions WHERE id=?',s))game.write('INSERT INTO sessions VALUES(?,?,?)',s,'csrf-token',now);return {db,game,advance:(n:number)=>{now+=n;},set:(n:number)=>{now=n;}};}
function complete(f:ReturnType<typeof fixture>,runId:string,session:string){for(let i=0;i<7;i++){const v=f.game.begin(runId,session);const snapshot=JSON.parse(f.game.owned(runId,session).snapshot);f.advance(3000);f.game.submit(runId,session,{index:i,answer:snapshot[i].answers.find((a:any)=>a.tier==='gem').canonical,requestId:`request-${i}`});}return f.game.state(runId,session);}
test('a bank, scoring or timer update cannot change an existing challenge',()=>{const f=fixture();const cid=f.game.createChallenge('creator',{});const runId=f.game.claim(cid,'friend','Bob');const original=JSON.parse(f.game.owned(runId,'friend').snapshot);for(const p of f.game.bank){p.version+=1;p.text='Replacement question';for(const a of p.answers)a.canonical='Replacement '+a.canonical;}f.game.readingMs=99999;f.game.answerMs=99999;const old=POINTS.gem;POINTS.gem=1;try{const v=f.game.begin(runId,'friend');assert.equal(v.prompt!.text,original[0].text);assert.equal(v.prompt!.version,original[0].version);assert.equal(v.deadline!-v.readingUntil!,25000);f.advance(3000);const result=f.game.submit(runId,'friend',{index:0,answer:original[0].answers.find((a:any)=>a.tier==='gem').canonical,requestId:'pinned-score'});assert.equal(result.outcome!.points,100);assert.deepEqual(JSON.parse(f.game.owned(runId,'friend').snapshot),original);}finally{POINTS.gem=old;f.db.close();}});
test('seven zero-score timeouts still produce a complete recap and insufficient content gives recovery',()=>{const f=fixture();const runId=f.game.createRun('creator',{});for(let i=0;i<7;i++){const v=f.game.begin(runId,'creator');f.set(v.deadline!+251);f.game.state(runId,'creator');}const result=f.game.state(runId,'creator');assert.equal(result.state,'complete');assert.equal(result.total,0);assert.equal(result.depth,0);assert.equal(result.recap!.length,7);f.game.bank=f.game.bank.slice(0,3);assert.throws(()=>f.game.createRun('creator',{}),/more categories/);f.db.close();});
test('seven perfect answers yield 700 points, 7000m, matching recap and a new unlimited run',()=>{const f=fixture();const id=f.game.createRun('creator',{});const v=complete(f,id,'creator');assert.equal(v.total,700);assert.equal(v.depth,7000);assert.equal(v.stageDepth,7000);assert.equal(v.state,'complete');assert.equal(v.recap!.reduce((n,o)=>n+o.points,0),700);assert.notEqual(f.game.createRun('creator',{}),id);f.db.close();});
test('blank timeout, near deadline, late submission, retries and revised answers commit only once',()=>{const f=fixture();const id=f.game.createRun('creator',{});let v=f.game.begin(id,'creator');const answer=JSON.parse(f.game.owned(id,'creator').snapshot)[0].answers[0].canonical;assert.throws(()=>f.game.submit(id,'creator',{index:0,answer,requestId:'early-attempt'}),/reading/);f.set(v.deadline!-1);v=f.game.submit(id,'creator',{index:0,answer,requestId:'near-deadline'});const score=v.total;f.advance(10000);assert.equal(f.game.submit(id,'creator',{index:0,answer:'different',requestId:'near-deadline'}).total,score);v=f.game.begin(id,'creator');f.set(v.deadline!+251);v=f.game.submit(id,'creator',{index:1,answer,requestId:'late-attempt'});assert.equal(v.outcome!.status,'timeout');assert.equal(v.outcome!.submitted,'');v=f.game.begin(id,'creator');f.set(v.deadline!+251);v=f.game.state(id,'creator');assert.equal(v.outcome!.status,'timeout');assert.equal(f.game.state(id,'creator').total,score);assert.equal(f.game.all('SELECT * FROM rounds WHERE run_id=?',id).length,3);f.db.close();});
test('50+ Endless prompts continue, stages reset, totals derive from rounds and untimed state never expires',()=>{const f=fixture();const id=f.game.createRun('creator',{mode:'endless'});for(let i=0;i<56;i++){const v=f.game.begin(id,'creator');const snapshot=JSON.parse(f.game.owned(id,'creator').snapshot);if(i%7===0)assert.equal(v.stageDepth,0);f.advance(3000);f.game.submit(id,'creator',{index:i,answer:snapshot[i].answers.find((a:any)=>a.tier==='gem').canonical,requestId:`endless-${i}`});}const v=f.game.state(id,'creator');assert.equal(v.answered,56);assert.equal(v.total,5600);assert.equal(v.depth,56000);assert.equal(v.state,'result');assert.equal(f.game.begin(id,'creator').round,56);f.advance(30000);f.game.state(id,'creator');assert.equal(f.game.endEndless(id,'creator').state,'complete');const practice=f.game.createRun('creator',{relaxed:true});f.game.begin(practice,'creator');f.advance(999999);assert.equal(f.game.state(practice,'creator').state,'answering');f.db.close();});
test('challenge slot is unique, prompt snapshots immutable, visibility enforced and equal scores draw',()=>{const f=fixture();const c=f.game.createChallenge('creator',{nickname:'Alice'});const r1=f.game.summary(c,'creator').runId;const r2=f.game.claim(c,'friend','Bob');assert.equal(f.game.claim(c,'friend','Changed'),r2);assert.throws(()=>f.game.claim(c,'third','Carol'),/two players/);assert.throws(()=>f.game.state(r1,'third'),/another browser/);assert.deepEqual(JSON.parse(f.game.owned(r1,'creator').snapshot),JSON.parse(f.game.owned(r2,'friend').snapshot));complete(f,r1,'creator');const hidden=f.game.summary(c,'friend');assert.equal(hidden.results,undefined);assert.equal(f.game.summary(c,'third').results,undefined);const first=f.game.begin(r2,'friend');assert.equal('answers' in first.prompt!,false);assert.equal(first.recap,undefined);f.game.bank[0].answers[0].canonical='CONTENT CHANGED';assert.notEqual(JSON.parse(f.game.owned(r2,'friend').snapshot)[0].answers[0].canonical,'CONTENT CHANGED');f.advance(30000);f.game.state(r2,'friend');for(let i=1;i<7;i++){const v=f.game.begin(r2,'friend');f.set(v.deadline!+251);f.game.state(r2,'friend');}const results=f.game.summary(c,'friend').results;assert.equal(results.length,2);assert.equal(results.find((p:any)=>p.role==='creator').total,700);assert.ok(results.find((p:any)=>p.role==='creator').recap[0].canonical);f.advance(31*86400000);assert.throws(()=>f.game.summary(c,'creator'),e=>e instanceof GameError&&e.status===410);assert.throws(()=>f.game.summary('unknown','creator'),/find this challenge/);f.db.close();});
test('after-play challenge uses verified original run; disk reopen preserves results and deadline',()=>{const folder=mkdtempSync(join(tmpdir(),'deep-trivia-test-'));const path=join(folder,'db.sqlite');const f=fixture(path);const r=f.game.createRun('creator',{});complete(f,r,'creator');const cid=f.game.createChallenge('creator',{runId:r,nickname:'Alice'});const friend=f.game.claim(cid,'friend','Bob');const begun=f.game.begin(friend,'friend');const original=JSON.parse(f.game.owned(r,'creator').snapshot);f.db.close();const next=fixture(path);assert.equal(next.game.state(friend,'friend').deadline,begun.deadline);assert.deepEqual(JSON.parse(next.game.owned(friend,'friend').snapshot),original);assert.equal(next.game.summary(cid,'creator').results[0].total,700);next.set(begun.deadline!+251);assert.equal(next.game.state(friend,'friend').outcome!.status,'timeout');next.db.close();rmSync(folder,{recursive:true});});
