import {q,refs as r} from './content-everyday-builder';
export const everydayTechnology=[
q('web-browsers','Technology','easy','Name a web browser.',r.tech,'Chrome^Google Chrome|Firefox^Mozilla Firefox|Safari|Edge^Microsoft Edge|Internet Explorer^IE|Opera|Brave;Vivaldi|Chromium|Tor Browser|Samsung Internet|UC Browser|Netscape Navigator^Netscape|Konqueror|Lynx|Links|Dillo|SeaMonkey|Pale Moon|Waterfox;Falkon|Midori|Epiphany^GNOME Web|K-Meleon|Maxthon|Otter Browser|Comodo Dragon|Yandex Browser|QQ Browser|Basilisk|Dooble|Arc|Mosaic|Amaya;NetSurf;Ladybird','broad','Current and historic web browsers; search engines alone are excluded.'),
q('programming-languages','Technology','easy','Name a programming language.',r.tech,'Python|Java|JavaScript^JS|C|C++|C#^C sharp|BASIC|PHP|Ruby|Swift;TypeScript|Go^Golang|Rust|Kotlin|R|Perl|Pascal|Fortran|COBOL|Lisp|Scheme|Haskell|Lua|Scala|Dart|Objective-C|Visual Basic|SQL|MATLAB|Assembly;Prolog|Erlang|Elixir|F#^F sharp|OCaml|Clojure|Groovy|Julia|Ada|D|Zig|Nim|Crystal|Smalltalk|Tcl|APL|Logo|Scratch|PowerShell|Bash;Raku;Forth','broad','Programming and query languages; HTML and CSS are markup or style languages, not accepted here.'),
q('file-extensions','Technology','easy','Name a computer file extension.',r.tech,'TXT^.txt|PDF^.pdf|DOC^.doc|DOCX^.docx|JPG^.jpg|JPEG^.jpeg|PNG^.png|GIF^.gif|MP3^.mp3|MP4^.mp4;XLS^.xls|XLSX^.xlsx|PPT^.ppt|PPTX^.pptx|CSV^.csv|ZIP^.zip|RAR^.rar|EXE^.exe|HTML^.html|CSS^.css|JS^.js|JSON^.json|XML^.xml|WAV^.wav|AVI^.avi|MOV^.mov|SVG^.svg|WEBP^.webp|BMP^.bmp|TIFF^.tiff;FLAC^.flac|OGG^.ogg|MKV^.mkv|WEBM^.webm|M4A^.m4a|AAC^.aac|EPUB^.epub|MOBI^.mobi|RTF^.rtf|ODT^.odt|ODS^.ods|ODP^.odp|TAR^.tar|GZ^.gz|7Z^.7z|ISO^.iso|DMG^.dmg|APK^.apk|PY^.py|TS^.ts|SQL^.sql|MD^.md;HEIC^.heic;AVIF^.avif','broad','Extension names with or without the leading dot; filenames alone are excluded.'),
q('operating-systems','Technology','easy','Name an operating system.',r.tech,'Windows|macOS^Mac OS|Linux|Android|iOS|ChromeOS^Chrome OS|Ubuntu|Debian;Fedora|Mint^Linux Mint|Arch Linux|openSUSE|Red Hat Enterprise Linux^RHEL|CentOS|FreeBSD|OpenBSD|NetBSD|Solaris|Unix|MS-DOS^DOS|OS/2|AmigaOS|RISC OS|Haiku;QNX|AIX|HP-UX|OpenVMS|ReactOS|Tizen|webOS|KaiOS|HarmonyOS|watchOS|tvOS|iPadOS|SteamOS|Elementary OS|Kali Linux|Manjaro|Gentoo|Slackware;Plan 9;TempleOS','broad','Current or historic systems and named Linux distributions.'),
q('keyboard-keys','Technology','easy','Name a non-letter keyboard key.',r.words,'Enter^Return|Space^Spacebar|Escape^Esc|Shift|Control^Ctrl|Alt|Tab|Backspace|Delete^Del|Caps Lock;Windows key|Command|Option|Fn|Insert|Home|End|Page Up|Page Down|Up arrow|Down arrow|Left arrow|Right arrow|Print Screen^PrtSc|Scroll Lock|Pause|Num Lock|F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12;Zero^0|One^1|Two^2|Three^3|Four^4|Five^5|Six^6|Seven^7|Eight^8|Nine^9|Plus|Minus|Equals|Comma|Full stop^Period|Slash|Backslash|Semicolon|Apostrophe|Backtick|Left bracket|Right bracket;Menu key;Compose key','broad','Key names on physical keyboards; any alphabet letter is excluded.'),
q('computer-components','Technology','easy','Name a computer hardware component.',r.words,'Processor^CPU|Memory^RAM|Hard drive^HDD|Graphics card^GPU|Motherboard|Monitor|Keyboard|Mouse|Power supply^PSU|Fan;SSD^Solid state drive|Network card|Sound card|Wi-Fi card|Heat sink|Case|USB port|Optical drive|DVD drive|CD drive|Webcam|Microphone|Speaker|Touchpad|Trackball|Joystick|Gamepad|Printer|Scanner|Router|Modem;RAM module|VRAM|CMOS battery|SATA cable|Ethernet port|HDMI port|DisplayPort|Card reader|Cooling pump|Liquid cooler|Expansion card|USB hub;RAID controller;Capture card','broad','Internal parts and peripherals; software is excluded.'),
q('game-consoles','Technology','easy','Name a video game console.','https://www.nintendo.com/en-gb/Hardware/Nintendo-History/Nintendo-History-625945.html','PlayStation^PS1|PlayStation 2^PS2|PlayStation 3^PS3|PlayStation 4^PS4|PlayStation 5^PS5|Xbox|Xbox 360|Xbox One|Xbox Series X|Xbox Series S|Nintendo Switch|Nintendo Switch 2^Switch 2|Wii|Game Boy;Wii U|Nintendo DS^DS|Nintendo 3DS^3DS|Nintendo 64^N64|NES^Nintendo Entertainment System|SNES^Super Nintendo|GameCube|Game Boy Advance^GBA|Game Boy Color|Sega Mega Drive^Genesis|Sega Master System|Dreamcast|Sega Saturn|Game Gear|Atari 2600|Atari 5200|Atari 7800;Atari Jaguar|Atari Lynx|Neo Geo|Neo Geo Pocket|TurboGrafx-16^PC Engine|3DO|Philips CD-i|ColecoVision|Intellivision|Magnavox Odyssey|Vectrex|Virtual Boy|PSP^PlayStation Portable|PS Vita;WonderSwan;Amstrad GX4000','broad','Named home or handheld console platforms, including historic models; PCs are excluded. Sony, Microsoft and Sega histories supplement the Nintendo source.'),
q('digital-storage','Technology','easy','Name a device or medium used to store digital data.',r.words,'Hard drive|SSD|USB stick^Flash drive|Memory card|CD|DVD|Blu-ray|Floppy disk|Magnetic tape|Cloud storage;SD card|microSD card|CompactFlash|Memory Stick|SmartMedia|xD card|Zip disk|Jaz disk|Magneto-optical disk|RAM|ROM|EPROM|EEPROM|USB hard drive|NAS|Tape cartridge|LTO tape|DAT tape|DVD-R|CD-R;DVD-RW|CD-RW|BD-R|BD-RE|Punch card|Punched tape|Core memory|Drum memory|Bubble memory|Cache memory;Delay-line memory;Holographic storage','broad','Modern or historic media and memory technologies; storage units such as megabyte are excluded.'),
q('html-headings','Technology','medium','Name an HTML heading element.', 'https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/Heading_Elements','h1^<h1>|h2^<h2>|h3^<h3>;h4^<h4>|h5^<h5>;;;h6^<h6>','complete','The six heading elements; angle brackets may be omitted.'),
q('web-request-methods','Technology','medium','Name a standard HTTP request method.','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Methods','GET|POST|PUT|DELETE;PATCH|HEAD|OPTIONS;TRACE;;CONNECT','complete','The nine standard methods documented by MDN; custom extensions are excluded.'),
q('osi-layers','Technology','hard','Name an OSI networking layer.','https://www.cloudflare.com/learning/ddos/glossary/open-systems-interconnection-model-osi/','Application|Network|Transport;Physical|Data link;Session;;Presentation','complete','The seven OSI layers, not the four-layer TCP/IP model.'),
q('sql-joins','Technology','hard','Name a common SQL join type.','https://www.postgresql.org/docs/current/queries-table-expressions.html','Inner join^Inner|Left join^Left outer join|Right join^Right outer join;Full join^Full outer join|Cross join;Self join;;Natural join','complete','The standard joins and the conventional self-join usage; implementation-specific joins are excluded.'),
];
