import {q,refs as r} from './content-everyday-builder';
export const everydayGeneral=[
q('weekdays','General knowledge','easy','Name a day of the week.',r.words,'Monday|Tuesday|Wednesday|Thursday|Friday|Saturday;;;Sunday','complete','The seven English weekday names; standard three-letter abbreviations count.'),
q('months','General knowledge','easy','Name a month.',r.words,'January|February|March|April|May|June|July|August;September|October|November;;;December','complete','The twelve Gregorian calendar months; standard abbreviations count.'),
q('zodiac-signs','General knowledge','easy','Name a Western zodiac sign.','https://www.britannica.com/topic/zodiac','Aries|Taurus|Gemini|Cancer|Leo|Virgo;Libra|Scorpio^Scorpius|Sagittarius|Capricorn^Capricornus|Aquarius;;;Pisces','complete','The traditional twelve astrological signs, not scientific predictions.'),
q('chinese-zodiac','General knowledge','easy','Name a Chinese zodiac animal.','https://www.britannica.com/topic/Chinese-zodiac','Rat|Ox|Tiger|Rabbit|Dragon|Snake|Horse|Goat^Sheep|Monkey;Rooster^Chicken|Dog;;;Pig^Boar','complete','The twelve animals in the traditional cycle.'),
q('roman-numerals','Language','easy','Name a Roman numeral symbol.','https://www.britannica.com/topic/Roman-numeral','I|V|X;L|C|M;;;D','complete','The seven standard single-letter symbols, not compound numerals.'),
q('new-seven-wonders','General knowledge','easy','Name one of the New Seven Wonders of the World.','https://world.new7wonders.com/wonders/','Great Wall of China^Great Wall|Colosseum|Taj Mahal|Machu Picchu;Christ the Redeemer|Petra;;;Chichén Itzá^Chichen Itza','complete','The seven chosen by the 2007 New7Wonders campaign; not the ancient list.'),
q('ancient-wonders','General knowledge','medium','Name an ancient Seven Wonder.','https://www.britannica.com/topic/Seven-Wonders-of-the-World','Great Pyramid of Giza^Great Pyramid|Hanging Gardens of Babylon^Hanging Gardens|Colossus of Rhodes;Lighthouse of Alexandria^Pharos|Statue of Zeus at Olympia;Temple of Artemis at Ephesus;;Mausoleum at Halicarnassus','complete','The traditional ancient list; the existence of the Hanging Gardens is historically debated.'),
q('santa-reindeer','General knowledge','easy','Name one of Santa’s traditional reindeer.','https://www.britannica.com/topic/Santa-Claus','Rudolph|Dasher|Dancer|Prancer|Vixen;Comet|Cupid;Donner^Donder;;Blitzen','complete','The eight from the traditional poem plus Rudolph.'),
q('currencies','General knowledge','easy','Name a currency.','https://www.iso.org/iso-4217-currency-codes.html','Pound sterling^Pound^GBP|US dollar^Dollar^USD|Euro^EUR|Japanese yen^Yen^JPY|Swiss franc^Franc^CHF|Chinese yuan^Yuan^Renminbi^CNY|Indian rupee^Rupee^INR|Russian rouble^Ruble^Rouble^RUB;Canadian dollar^CAD|Australian dollar^AUD|New Zealand dollar^NZD|South African rand^Rand^ZAR|Brazilian real^Real^BRL|Mexican peso^Peso^MXN|Turkish lira^Lira^TRY|Swedish krona^SEK|Norwegian krone^NOK|Danish krone^DKK|Polish zloty^Zloty^PLN|Czech koruna^CZK|Hungarian forint^Forint^HUF|Thai baht^Baht^THB|South Korean won^Won^KRW|Indonesian rupiah^Rupiah^IDR;Malaysian ringgit^Ringgit^MYR|Singapore dollar^SGD|Vietnamese dong^Dong^VND|Philippine peso^PHP|Israeli shekel^Shekel^ILS|Saudi riyal^Riyal^SAR|UAE dirham^Dirham^AED|Egyptian pound^EGP|Nigerian naira^Naira^NGN|Kenyan shilling^Shilling^KES|Ghanaian cedi^Cedi^GHS|Argentine peso^ARS|Chilean peso^CLP|Peruvian sol^Sol^PEN|Colombian peso^COP|Icelandic krona^ISK;Georgian lari^Lari^GEL|Armenian dram^Dram^AMD;Bhutanese ngultrum^Ngultrum^BTN','broad','Currency names, familiar umbrella names and ISO codes; old currencies can be reported if missing.'),
q('colours','General knowledge','easy','Name a colour.',r.words,'Red|Blue|Green|Yellow|Orange|Purple|Pink|Brown|Black|White|Grey^Gray;Violet|Indigo|Turquoise|Teal|Navy|Maroon|Burgundy|Beige|Cream|Gold|Silver|Bronze|Crimson|Scarlet|Magenta|Cyan|Lime|Olive|Coral|Salmon|Peach|Lavender|Lilac|Mauve;Amber|Ochre^Ocher|Khaki|Ivory|Ecru|Tan|Taupe|Sienna|Umber|Cerulean|Azure|Cobalt|Ultramarine|Chartreuse|Vermilion|Fuchsia;Aubergine;Viridian','broad','Established colour words; invented names and brand paint codes are excluded.'),
q('occupations','General knowledge','easy','Name a job or occupation.',r.words,'Teacher|Doctor|Nurse|Police officer|Firefighter|Chef|Farmer|Builder|Driver|Shop assistant;Dentist|Vet^Veterinarian|Lawyer|Accountant|Engineer|Scientist|Artist|Actor|Singer|Musician|Writer|Journalist|Librarian|Mechanic|Electrician|Plumber|Carpenter|Painter|Decorator|Hairdresser|Barber|Cleaner|Waiter|Baker|Butcher|Pilot|Sailor|Soldier|Postman^Postal worker|Receptionist;Secretary|Architect|Surveyor|Optician|Pharmacist|Physiotherapist|Paramedic|Midwife|Social worker|Counsellor^Counselor|Psychologist|Programmer|Designer|Translator|Interpreter|Florist|Gardener|Fisherman|Miner|Welder|Tailor|Photographer|Producer|Director|Curator|Archivist|Economist|Geologist|Meteorologist|Astronomer;Cartographer|Actuary|Radiographer|Audiologist;Cooper','broad','Established occupations, including trades and professions; personal names are excluded.'),
q('us-presidents','General knowledge','medium','Name a US president.','https://www.whitehousehistory.org/collections/president-biographies','George Washington^Washington|Abraham Lincoln^Lincoln|Barack Obama^Obama|Donald Trump^Trump|Joe Biden^Biden|John F Kennedy^JFK|Ronald Reagan^Reagan|Bill Clinton^Clinton|George W Bush;Thomas Jefferson^Jefferson|Theodore Roosevelt^Teddy Roosevelt|Franklin D Roosevelt^FDR|Harry Truman^Truman|Dwight Eisenhower^Eisenhower|Richard Nixon^Nixon|Gerald Ford^Ford|Jimmy Carter^Carter|George H W Bush|Woodrow Wilson^Wilson|Ulysses S Grant^Grant|Andrew Jackson;John Adams|James Madison|James Monroe|John Quincy Adams|Martin Van Buren|William Henry Harrison|John Tyler|James K Polk|Zachary Taylor|Millard Fillmore|Franklin Pierce|James Buchanan|Andrew Johnson|Rutherford B Hayes|James Garfield|Chester Arthur|Grover Cleveland|Benjamin Harrison|William Howard Taft|Warren Harding|Calvin Coolidge;Herbert Hoover;William McKinley^McKinley','complete','People who held the office through 2025; Cleveland and Trump each count once, not twice.'),
q('greek-muses','Culture','hard','Name one of the nine Greek Muses.','https://www.theoi.com/Ouranios/Mousai.html','Calliope|Clio;Erato|Euterpe|Melpomene|Thalia;Terpsichore|Urania;;Polyhymnia','complete','The traditional nine Muses; other Greek deities are excluded.'),
q('precious-metals','General knowledge','medium','Name a conventional precious metal.','https://www.britannica.com/science/precious-metal','Gold|Silver|Platinum;Palladium|Rhodium|Iridium;Ruthenium;;Osmium','complete','Gold, silver and the six platinum-group metals; radioactive metals are excluded.'),
q('si-base-quantities','Science','medium','Name an SI base quantity.','https://www.bipm.org/en/publications/si-brochure','Length|Mass|Time|Temperature^Thermodynamic temperature;Electric current|Amount of substance;;;Luminous intensity','complete','The seven physical quantities, not their unit names.'),
];
