import {q,refs as r} from './content-everyday-builder';
export const everydaySport=[
q('swimming-strokes','Sport','easy','Name a competitive swimming stroke.','https://www.worldaquatics.com/swimming','Freestyle^Front crawl|Backstroke|Breaststroke;;;Butterfly','complete','The four competitive stroke categories.'),
q('football-positions','Sport','easy','Name a main football position.', 'https://www.thefa.com/','Goalkeeper^Keeper|Defender|Midfielder;;;Forward^Striker','complete','The four main position groups; specialised roles belong to these groups.'),
q('basketball-positions','Sport','easy','Name a standard basketball position.','https://www.nba.com/','Point guard|Shooting guard|Centre^Center;Small forward;;;Power forward','complete','The five traditional positions, not hybrid labels.'),
q('snooker-colours','Sport','easy','Name a ball colour in snooker.','https://wpbsa.com/play/','Red|Yellow|Green|Brown|Blue|Black;;;Pink','complete','All seven colours used in standard snooker.'),
q('rugby-scoring','Sport','easy','Name a way to score in rugby union.','https://www.world.rugby/the-game/laws/','Try|Conversion|Penalty^Penalty goal;Drop goal;;;Penalty try','complete','The five named scoring outcomes; rugby league rules differ.'),
q('rugby-positions','Sport','medium','Name a rugby union position.','https://www.world.rugby/the-game/laws/','Prop|Hooker|Lock|Flanker|Number eight^Number 8|Scrum-half^Scrum half|Fly-half^Fly half|Centre^Center|Wing|Full-back^Fullback;Loosehead prop|Tighthead prop|Blindside flanker|Openside flanker|Inside centre^Inside center;;;Outside centre^Outside center','complete','Standard XV roles, including umbrella position names.'),
q('cricket-dismissals','Sport','medium','Name a way a batter can be out in cricket.','https://www.lords.org/mcc/the-laws-of-cricket','Bowled|Caught|Run out|LBW^Leg before wicket|Stumped;Hit wicket|Hit the ball twice^Hit ball twice|Retired out;Obstructing the field;;Timed out','complete','Current dismissal types; handled the ball was merged into obstructing the field.'),
q('cricket-fielding','Sport','medium','Name a cricket fielding position.','https://www.lords.org/mcc/the-laws-of-cricket','Wicketkeeper|Slip|Gully|Point|Cover|Mid-off|Mid-on|Midwicket|Square leg|Fine leg;Third man|Backward point|Extra cover|Long-off|Long-on|Deep cover|Deep midwicket|Deep square leg|Backward square leg|Short leg|Leg slip|Silly point|Silly mid-off|Silly mid-on|Short third man|Short fine leg|Long leg|Deep point|Deep extra cover|Cover point;First slip|Second slip|Third slip|Fourth slip|Fly slip|Forward short leg|Backward short leg|Long stop|Deep backward point|Deep fine leg;Cow corner;Sweeper cover','broad','Established position names; any correctly named fielding position fits the category.'),
q('martial-arts','Sport','easy','Name a martial art.',r.sport,'Karate|Judo|Taekwondo|Kung fu|Boxing|Kickboxing|Wrestling|Aikido|Jujitsu^Jiu jitsu|Muay Thai;Brazilian jiu-jitsu^BJJ|Tai chi|Kendo|Krav Maga|Capoeira|Sumo|Sambo|Savate|Hapkido|Wing chun|Jeet kune do|Wushu|Tang soo do|Kenpo|Ninjutsu|Iaido|Kyudo|Eskrima^Arnis|Silat|Pencak silat;Shorinji kempo|Baguazhang|Xingyiquan|Bartitsu|Lethwei|Bokator|Gatka|Kalaripayattu|Kuk sool won|Ssireum;Taekkyeon;Dambe','broad','Established martial arts and combat-sport traditions, not individual moves.'),
q('tennis-shot-types','Sport','easy','Name a tennis shot or stroke.','https://www.itftennis.com/en/','Forehand|Backhand|Serve|Volley|Smash^Overhead|Lob|Drop shot|Slice;Half volley|Return|Passing shot|Approach shot|Topspin shot|Flat shot|Kick serve|Slice serve|Flat serve|Backhand volley|Forehand volley|Backhand slice|Forehand slice|Two-handed backhand|One-handed backhand|Inside-out forehand|Inside-in forehand|Drive volley^Swinging volley|Drop volley|Defensive lob;Topspin lob|Underarm serve|Backhand smash|Tweener|Buggy-whip forehand^Reverse forehand|Moonball|Block return|Chip return;SABR;Around-the-net shot','broad','Established shot names and recognised shot variants.'),
];
