import type {Prompt} from '../src/shared/types';
import {p} from './content-builder';
import {geography} from './content-geography';
import {science} from './content-science';
import {nature} from './content-nature';
import {food} from './content-food';
import {language} from './content-language';
import {culture} from './content-culture';
import {film} from './content-film';
import {sport} from './content-sport';
import {everydayFood} from './content-everyday-food';
import {everydayAnimals} from './content-everyday-animals';
import {everydayHome} from './content-everyday-home';
import {everydayGeography} from './content-everyday-geography';
import {everydayScience} from './content-everyday-science';
import {everydayTechnology} from './content-everyday-technology';
import {everydayTransport} from './content-everyday-transport';
import {everydayGeneral} from './content-everyday-general';
import {everydayEntertainment} from './content-everyday-entertainment';
import {expandLegacy} from './content-expansion';
import {everydayExtra} from './content-everyday-extra';
import {everydaySport} from './content-everyday-sport';
import {reviewPrompt} from './content-review';
const un='https://www.un.org/about-us/member-states';
const rsc='https://periodic-table.rsc.org/';
const geo='https://unstats.un.org/unsd/methodology/m49/';
const legacy:Prompt[]=[
 ...geography,...science,...nature,...food,...language,...culture,...film,...sport,
 p('africa','Geography','Name a UN member country in Africa.','UN M49 geographic classification; only UN member states, not territories.',geo,'Egypt|South Africa|Kenya|Nigeria|Morocco|Ghana|Ethiopia|Tunisia|Algeria|Tanzania|Uganda|Zimbabwe|Zambia|Senegal|Cameroon|Angola|Botswana|Rwanda|Mozambique|Madagascar|Sudan|South Sudan|Libya|Namibia|Mali|Niger|Chad|Benin|Togo|Liberia|Sierra Leone|Guinea|Guinea-Bissau|Equatorial Guinea|Gabon|Republic of the Congo^Congo-Brazzaville|Democratic Republic of the Congo^DR Congo^DRC^Congo-Kinshasa|Burkina Faso|Burundi|Malawi|Lesotho|Eswatini^Swaziland|Somalia|Eritrea|Djibouti|Mauritania|The Gambia^Gambia|Mauritius|Seychelles|Cabo Verde^Cape Verde|Comoros|São Tomé and Príncipe^Sao Tome and Principe|Central African Republic^CAR|Côte d’Ivoire^Ivory Coast','São Tomé and Príncipe'),
 p('asia','Geography','Name a UN member country in Asia.','UN M49 classification: includes Türkiye, Cyprus and Russia is excluded (classified in Europe).',geo,'China|India|Japan|Thailand|Vietnam|Indonesia|Malaysia|Singapore|South Korea^Republic of Korea|North Korea^Democratic Peoples Republic of Korea|Pakistan|Bangladesh|Sri Lanka|Nepal|Bhutan|Maldives|Mongolia|Cambodia|Laos^Lao Peoples Democratic Republic|Myanmar^Burma|Philippines|Brunei^Brunei Darussalam|Timor-Leste^East Timor|Kazakhstan|Uzbekistan|Kyrgyzstan|Tajikistan|Turkmenistan|Afghanistan|Iran|Iraq|Saudi Arabia|United Arab Emirates^UAE|Oman|Yemen|Qatar|Bahrain|Kuwait|Jordan|Israel|Lebanon|Syria|Türkiye^Turkey|Cyprus|Armenia|Azerbaijan|Georgia','Timor-Leste'),
 p('europe','Geography','Name a UN member country in Europe.','UN M49 geographic classification. Türkiye and Cyprus belong to Asia in this scheme; Kosovo is not a UN member.',geo,'United Kingdom^UK^Britain^Great Britain|France|Germany|Italy|Spain|Portugal|Ireland|Netherlands^Holland|Belgium|Switzerland|Austria|Sweden|Norway|Denmark|Finland|Iceland|Greece|Poland|Czechia^Czech Republic|Slovakia|Hungary|Romania|Bulgaria|Croatia|Slovenia|Serbia|Montenegro|Bosnia and Herzegovina^Bosnia|North Macedonia^Macedonia|Albania|Estonia|Latvia|Lithuania|Belarus|Ukraine|Russia^Russian Federation|Moldova|Malta|Luxembourg|Andorra|Monaco|Liechtenstein|San Marino','San Marino'),
 p('americas','Geography','Name a UN member country in the Americas.','North, Central and South America and the Caribbean; UN member states only.',geo,'United States^USA^US^United States of America|Canada|Mexico|Brazil|Argentina|Chile|Peru|Colombia|Venezuela|Ecuador|Bolivia|Uruguay|Paraguay|Costa Rica|Panama|Guatemala|Honduras|El Salvador|Nicaragua|Belize|Cuba|Jamaica|Haiti|Dominican Republic|The Bahamas^Bahamas|Barbados|Trinidad and Tobago|Guyana|Suriname|Dominica|Grenada|Saint Lucia^St Lucia|Saint Vincent and the Grenadines^St Vincent and the Grenadines|Saint Kitts and Nevis^St Kitts and Nevis|Antigua and Barbuda','Saint Kitts and Nevis'),
 p('oceania','Geography','Name a UN member country in Oceania.','UN M49 classification. This closed set has 14 members; territories and freely associated non-members are excluded.',geo,'Australia|New Zealand|Fiji|Papua New Guinea^PNG|Samoa|Tonga|Vanuatu|Solomon Islands|Kiribati|Tuvalu|Nauru|Palau|Marshall Islands|Federated States of Micronesia^Micronesia','Kiribati'),
 p('mediterranean','Geography','Name a UN member country with a Mediterranean coastline.','Includes the Adriatic and Aegean seas, and island states. Does not include Red Sea or Black Sea coast alone.',un,'France|Spain|Italy|Greece|Türkiye^Turkey|Egypt|Morocco|Algeria|Tunisia|Libya|Israel|Lebanon|Syria|Croatia|Slovenia|Bosnia and Herzegovina^Bosnia|Montenegro|Albania|Cyprus|Malta|Monaco','Bosnia and Herzegovina'),
 p('landlocked','Geography','Name a landlocked UN member country.','No coastline on an ocean or connected sea. Caspian Sea shores still count as landlocked.',un,'Switzerland|Austria|Hungary|Nepal|Mongolia|Bolivia|Paraguay|Laos|Bhutan|Afghanistan|Kazakhstan|Uzbekistan|Kyrgyzstan|Tajikistan|Turkmenistan|Armenia|Azerbaijan|Belarus|Czechia^Czech Republic|Slovakia|Serbia|North Macedonia|Moldova|Luxembourg|Liechtenstein|Andorra|San Marino|Botswana|Burkina Faso|Burundi|Central African Republic^CAR|Chad|Eswatini^Swaziland|Ethiopia|Lesotho|Malawi|Mali|Niger|Rwanda|South Sudan|Uganda|Zambia|Zimbabwe','Lesotho'),
 p('us-states','Geography','Name one of the 50 US states.','State names only; Washington DC and US territories are excluded. Common postal abbreviations are accepted.', 'https://www.census.gov/library/reference/code-lists/ansi.html','California^CA|Texas^TX|Florida^FL|New York^NY|Hawaii^HI|Alaska^AK|Washington^WA|Nevada^NV|Arizona^AZ|Colorado^CO|Illinois^IL|Massachusetts^MA|Georgia^GA|Ohio^OH|Michigan^MI|Pennsylvania^PA|New Jersey^NJ|Virginia^VA|North Carolina^NC|South Carolina^SC|Oregon^OR|Tennessee^TN|Alabama^AL|Louisiana^LA|Kentucky^KY|Wisconsin^WI|Minnesota^MN|Missouri^MO|Maryland^MD|Connecticut^CT|Utah^UT|Kansas^KS|Oklahoma^OK|Indiana^IN|Iowa^IA|Arkansas^AR|Mississippi^MS|Nebraska^NE|New Mexico^NM|West Virginia^WV|Idaho^ID|Maine^ME|New Hampshire^NH|Vermont^VT|Rhode Island^RI|Delaware^DE|South Dakota^SD|North Dakota^ND|Montana^MT|Wyoming^WY','Wyoming'),
 p('elements','Science','Name a chemical element.','The 118 IUPAC named elements. Element names and current symbols are accepted.',rsc,'Hydrogen^H|Oxygen^O|Carbon^C|Gold^Au|Silver^Ag|Iron^Fe|Helium^He|Nitrogen^N|Copper^Cu|Calcium^Ca|Sodium^Na|Chlorine^Cl|Aluminium^Al^Aluminum|Sulfur^S^Sulphur|Potassium^K|Magnesium^Mg|Silicon^Si|Zinc^Zn|Tin^Sn|Lead^Pb|Mercury^Hg|Neon^Ne|Lithium^Li|Fluorine^F|Phosphorus^P|Boron^B|Beryllium^Be|Argon^Ar|Nickel^Ni|Cobalt^Co|Chromium^Cr|Manganese^Mn|Titanium^Ti|Platinum^Pt|Uranium^U|Iodine^I|Bromine^Br|Strontium^Sr|Barium^Ba|Radium^Ra|Radon^Rn|Xenon^Xe|Krypton^Kr|Selenium^Se|Arsenic^As|Cadmium^Cd|Palladium^Pd|Tungsten^W|Vanadium^V|Zirconium^Zr|Molybdenum^Mo|Rubidium^Rb|Caesium^Cs^Cesium|Gallium^Ga|Germanium^Ge|Indium^In|Antimony^Sb|Tellurium^Te|Scandium^Sc|Yttrium^Y|Lanthanum^La|Cerium^Ce|Praseodymium^Pr|Neodymium^Nd|Promethium^Pm|Samarium^Sm|Europium^Eu|Gadolinium^Gd|Terbium^Tb|Dysprosium^Dy|Holmium^Ho|Erbium^Er|Thulium^Tm|Ytterbium^Yb|Lutetium^Lu|Hafnium^Hf|Tantalum^Ta|Rhenium^Re|Osmium^Os|Iridium^Ir|Thallium^Tl|Bismuth^Bi|Polonium^Po|Astatine^At|Francium^Fr|Actinium^Ac|Thorium^Th|Protactinium^Pa|Neptunium^Np|Plutonium^Pu|Americium^Am|Curium^Cm|Berkelium^Bk|Californium^Cf|Einsteinium^Es|Fermium^Fm|Mendelevium^Md|Nobelium^No|Lawrencium^Lr|Rutherfordium^Rf|Dubnium^Db|Seaborgium^Sg|Bohrium^Bh|Hassium^Hs|Meitnerium^Mt|Darmstadtium^Ds|Roentgenium^Rg|Copernicium^Cn|Nihonium^Nh|Flerovium^Fl|Moscovium^Mc|Livermorium^Lv|Tennessine^Ts|Oganesson^Og|Technetium^Tc','Meitnerium'),
 p('one-letter-elements','Science','Name an element with a one-letter symbol.','Use its name or symbol. There are 14 current one-letter symbols.',rsc,'Hydrogen^H|Carbon^C|Oxygen^O|Nitrogen^N|Sulfur^S^Sulphur|Potassium^K|Fluorine^F|Phosphorus^P|Boron^B|Iodine^I|Uranium^U|Vanadium^V|Tungsten^W|Yttrium^Y','Yttrium'),
 p('noble-gases','Science','Name a group 18 element.','The IUPAC group 18 column, conventionally called noble gases, including synthetic oganesson.',rsc,'Helium^He|Neon^Ne|Argon^Ar|Krypton^Kr|Xenon^Xe|Radon^Rn|Oganesson^Og','Oganesson'),
 p('si-units','Science','Name an SI unit with a special name.','The seven base units or one of 22 named derived units; prefixes such as kilometre are excluded. Names and unambiguous symbols accepted; symbols that collide when case is ignored are omitted.','https://www.bipm.org/en/publications/si-brochure','Metre^Meter^m|Second^s|Kilogram^kg|Ampere^Amp^A|Kelvin^K|Mole^mol|Candela^cd|Hertz^Hz|Newton^N|Pascal^Pa|Joule^J|Watt^W|Coulomb^C|Volt^V|Farad^F|Ohm^Ω|Siemens^S|Weber^Wb|Tesla^T|Henry^H|Degree Celsius^Celsius^°C|Lumen^lm|Lux^lx|Becquerel^Bq|Gray^Gy|Sievert^Sv|Katal^kat|Radian^rad|Steradian^sr','Katal'),
 p('constellations','Science','Name an officially recognised constellation.','The 88 IAU constellations; English translations and Latin names are accepted where listed.','https://www.iau.org/IAU/IAU/Astronomy-FAQs/Constellations.aspx','Orion|Ursa Major^Great Bear|Ursa Minor^Little Bear|Cassiopeia|Andromeda|Leo|Scorpius^Scorpio|Taurus|Gemini|Cancer|Virgo|Libra|Sagittarius|Capricornus^Capricorn|Aquarius|Pisces|Aries|Cygnus^Swan|Lyra|Aquila^Eagle|Pegasus|Perseus|Draco|Hercules|Canis Major^Greater Dog|Canis Minor^Lesser Dog|Centaurus|Crux^Southern Cross|Carina|Vela|Puppis|Ophiuchus|Serpens|Cetus|Eridanus|Hydra|Lepus|Auriga|Boötes^Bootes|Corona Borealis|Corona Australis|Delphinus|Sagitta|Triangulum|Triangulum Australe|Piscis Austrinus|Lupus|Ara|Pavo|Tucana|Grus|Phoenix|Indus|Apus|Chamaeleon|Dorado|Volans|Mensa|Reticulum|Hydrus|Octans|Musca|Circinus|Norma|Telescopium|Microscopium|Sculptor|Fornax|Caelum|Horologium|Pictor|Columba|Pyxis|Antlia|Monoceros|Sextans|Crater|Corvus|Coma Berenices|Canes Venatici|Lacerta|Vulpecula|Scutum|Equuleus|Camelopardalis|Lynx|Leo Minor','Reticulum'),
 p('planets','Science','Name a planet or IAU-recognised dwarf planet in our Solar System.','Eight planets and five recognised dwarf planets. Moons and candidate dwarf planets are excluded.','https://science.nasa.gov/solar-system/','Earth|Mars|Jupiter|Saturn|Venus|Mercury|Neptune|Uranus|Pluto|Ceres|Eris|Haumea|Makemake','Makemake'),
 p('penguins','Nature','Name a penguin species breeding in UK Overseas Territories.','The nine species listed by the RSPB; a specific species name is needed.','https://www.rspb.org.uk/whats-happening/news/how-to-count-penguins','Emperor penguin^Emperor|King penguin^King|Gentoo penguin^Gentoo|Adélie penguin^Adelie|Chinstrap penguin^Chinstrap|Macaroni penguin^Macaroni|Magellanic penguin^Magellanic|Southern rockhopper penguin^Southern rockhopper|Northern rockhopper penguin^Northern rockhopper','Northern rockhopper penguin'),
 p('british-birds','Nature','Name a bird on the RSPB UK bird guide.','A species, not a broad group such as duck; this curated list may not include every valid species.','https://www.rspb.org.uk/birds-and-wildlife/a-z','Robin^European robin|Blackbird^Common blackbird|Blue tit|Great tit|House sparrow|Woodpigeon^Wood pigeon|Magpie^Eurasian magpie|Carrion crow|Mallard|Mute swan|Canada goose|Starling^Common starling|Chaffinch|Goldfinch|Greenfinch|Wren^Eurasian wren|Dunnock|Song thrush|Mistle thrush|Long-tailed tit|Coal tit|Nuthatch|Treecreeper|Great spotted woodpecker|Green woodpecker|Kingfisher^Common kingfisher|Barn owl|Tawny owl|Little owl|Buzzard^Common buzzard|Kestrel^Common kestrel|Peregrine falcon^Peregrine|Red kite|Sparrowhawk|Heron^Grey heron|Cormorant^Great cormorant|Puffin^Atlantic puffin|Gannet^Northern gannet|Guillemot^Common guillemot|Razorbill|Lapwing^Northern lapwing|Curlew^Eurasian curlew|Oystercatcher^Eurasian oystercatcher|Redshank^Common redshank|Snipe^Common snipe|Skylark^Eurasian skylark|Swallow^Barn swallow|House martin|Swift^Common swift|Wheatear^Northern wheatear|Dipper^White-throated dipper|Waxwing^Bohemian waxwing|Chough^Red-billed chough','Chough'),
 p('garden-plants','Nature','Name a flowering plant genus in the RHS plant finder.','Genus-level common names are accepted where unambiguous in this list; the curated bank is not exhaustive.','https://www.rhs.org.uk/plants/search-results/widgets','Rosa^Rose^Roses|Tulipa^Tulip^Tulips|Narcissus^Daffodil^Daffodils|Lilium^Lily^Lilies|Dahlia^Dahlias|Lavandula^Lavender|Helianthus^Sunflower^Sunflowers|Hydrangea|Camellia|Rhododendron|Magnolia|Clematis|Wisteria|Iris|Paeonia^Peony^Peonies|Fuchsia|Begonia|Petunia|Pelargonium|Geranium|Salvia|Verbena|Primula|Viola|Digitalis^Foxglove|Delphinium|Aquilegia^Columbine|Helleborus^Hellebore|Anemone|Echinacea^Coneflower|Rudbeckia|Cosmos|Zinnia|Lobelia|Lupinus^Lupin|Calendula|Tagetes|Alcea^Hollyhock|Antirrhinum^Snapdragon|Erysimum^Wallflower|Euphorbia|Agapanthus|Alstroemeria|Crocosmia|Kniphofia^Red hot poker|Gaura|Dicentra|Astilbe|Heuchera|Penstemon','Kniphofia'),
 p('tree-genera','Nature','Name a tree genus grown in British gardens.','Genus names or the listed common names; broad generic names may be ambiguous. This is a curated list.','https://www.rhs.org.uk/plants/types/trees','Quercus^Oak|Acer^Maple|Betula^Birch|Fagus^Beech|Fraxinus^Ash|Ulmus^Elm|Salix^Willow|Populus^Poplar|Pinus^Pine|Abies^Fir|Picea^Spruce|Larix^Larch|Cedrus^Cedar|Taxus^Yew|Ilex^Holly|Sorbus^Rowan|Crataegus^Hawthorn|Prunus^Cherry|Malus^Apple|Pyrus^Pear|Alnus^Alder|Corylus^Hazel|Carpinus^Hornbeam|Tilia^Lime^Linden|Aesculus^Horse chestnut|Castanea^Sweet chestnut|Juglans^Walnut|Magnolia|Ginkgo|Liquidambar^Sweetgum|Liriodendron^Tulip tree|Sequoiadendron^Giant sequoia|Sequoia^Coast redwood|Metasequoia^Dawn redwood|Paulownia|Catalpa|Cercis^Judas tree|Amelanchier|Zelkova|Nyssa^Tupelo','Metasequoia'),
 p('pasta','Food','Name an Italian pasta shape.','A pasta shape, not a sauce or complete dish. Curated aliases include common English names.','https://www.barilla.com/en-us/products/pasta','Spaghetti|Penne|Fusilli|Macaroni|Lasagne^Lasagna|Farfalle^Bow ties^Bow tie|Tagliatelle|Linguine|Fettuccine^Fettucine|Ravioli|Tortellini|Rigatoni|Cannelloni|Orzo^Risoni|Conchiglie^Shells|Orecchiette|Bucatini|Pappardelle|Vermicelli|Capellini^Angel hair|Ditalini|Rotini|Cavatappi|Gemelli|Ziti|Stelline|Fregola^Fregula|Mafaldine|Paccheri|Casarecce|Cavatelli|Garganelli|Trofie|Anellini|Acini di pepe|Fusilloni|Tortiglioni|Mezze penne|Sedanini|Campanelle','Garganelli'),
 p('herbs','Food','Name a culinary herb or spice.','Names used for edible seasoning; blends such as curry powder are excluded. Curated, non-exhaustive list.','https://www.kew.org/read-and-watch/plants-in-food','Basil|Parsley|Mint|Rosemary|Thyme|Oregano|Sage|Coriander^Cilantro|Chives|Dill|Bay leaf^Bay|Tarragon|Marjoram|Chervil|Lovage|Sorrel|Fennel|Cumin|Turmeric|Ginger|Cinnamon|Nutmeg|Clove^Cloves|Black pepper^Pepper|White pepper|Cardamom|Saffron|Paprika|Cayenne pepper^Cayenne|Allspice|Star anise|Anise^Aniseed|Caraway|Fenugreek|Mustard seed^Mustard|Sumac|Juniper berry^Juniper|Mace|Nigella^Black cumin|Asafoetida^Hing|Sichuan pepper^Szechuan pepper|Galangal|Lemongrass|Vanilla|Tonka bean','Asafoetida'),
 p('citrus','Food','Name a citrus fruit or named citrus hybrid.','Recognised culinary fruit names; named varieties count where listed. Not an exhaustive cultivar list.','https://citrusvariety.ucr.edu/citrus-varieties','Orange^Sweet orange|Lemon|Lime|Grapefruit|Mandarin|Tangerine|Clementine|Satsuma|Pomelo^Pummelo|Kumquat|Bergamot|Citron|Yuzu|Ugli fruit^Ugli|Tangelo|Blood orange|Seville orange^Bitter orange|Key lime|Persian lime|Meyer lemon|Calamondin^Calamansi|Sudachi|Kabosu|Finger lime|Limequat|Oroblanco^Sweetie|Minneola|Navel orange|Kinnow','Sudachi'),
 p('breads','Food','Name a type of bread.','Named bread styles, not brand names or sandwich fillings. The curated list is not exhaustive.','https://www.kingarthurbaking.com/recipes/bread','Baguette|Sourdough|Naan|Pitta^Pita|Ciabatta|Focaccia|Brioche|Bagel|Rye bread|Wholemeal bread^Whole wheat bread|White bread|Soda bread|Cornbread|Challah|Chapati^Roti|Paratha|Lavash|Tortilla|Pumpernickel|Flatbread|Bannock|Injera|Damper|Crumpet|English muffin|Pretzel|Bialy|Lefse|Matzo^Matzah|Pain de mie|Pan de cristal|Broa|Pão de queijo^Pao de queijo|Zopf|Stollen|Panettone|Pandesal|Mantou|Hokkaido milk bread^Milk bread','Bialy'),
 p('cheese','Food','Name a cheese style.','Named cheese styles, not generic milk or brands. Curated, non-exhaustive list; regional spellings accepted.','https://www.cheese.com/','Cheddar|Mozzarella|Brie|Camembert|Feta|Parmesan^Parmigiano Reggiano|Gouda|Edam|Emmental^Emmentaler|Stilton|Roquefort|Gorgonzola|Ricotta|Mascarpone|Halloumi|Manchego|Gruyère^Gruyere|Monterey Jack|Colby|Provolone|Pecorino Romano|Paneer|Cottage cheese|Cream cheese|Burrata|Comté^Comte|Reblochon|Taleggio|Fontina|Wensleydale|Red Leicester|Double Gloucester|Cheshire|Lancashire|Caerphilly|Dolcelatte|Mimolette|Ossau-Iraty|Havarti|Limburger|Quark|Époisses^Epoisses|Valençay^Valencay','Valençay'),
 p('greek-letters','Language','Name a letter of the Greek alphabet.','The standard 24 Greek letters; names or Greek glyphs are accepted.','https://www.britannica.com/topic/Greek-alphabet','Alpha^α|Beta^β|Gamma^γ|Delta^δ|Epsilon^ε|Zeta^ζ|Eta^η|Theta^θ|Iota^ι|Kappa^κ|Lambda^λ|Mu^μ|Nu^ν|Xi^ξ|Omicron^ο|Pi^π|Rho^ρ|Sigma^σ^ς|Tau^τ|Upsilon^υ|Phi^φ|Chi^χ|Psi^ψ|Omega^ω','Xi'),
 p('nato-alphabet','Language','Name a word in the NATO phonetic alphabet.','The 26 ICAO/NATO spelling words. Letter names alone do not count.','https://www.nato.int/cps/en/natohq/declassified_136216.htm','Alpha^Alfa|Bravo|Charlie|Delta|Echo|Foxtrot|Golf|Hotel|India|Juliett^Juliet|Kilo|Lima|Mike|November|Oscar|Papa|Quebec|Romeo|Sierra|Tango|Uniform|Victor|Whiskey^Whisky|X-ray^Xray|Yankee|Zulu','Juliett'),
 p('irregular-past','Language','Give an irregular English past-tense verb form.','Simple past forms, not past participles unless identical. This is a curated list; alternative British forms are included.','https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/irregular-verbs','Went|Was|Were|Had|Did|Saw|Said|Made|Took|Came|Got|Gave|Ate|Drank|Ran|Sat|Stood|Fell|Found|Thought|Bought|Brought|Caught|Taught|Fought|Slept|Kept|Left|Felt|Met|Sent|Spent|Built|Cut|Put|Set|Read|Wrote|Rode|Drove|Broke|Spoke|Chose|Rose|Froze|Stole|Wore|Swore|Tore|Knew|Grew|Threw|Flew|Blew|Drew|Swam|Sang|Rang|Began|Shook|Sank|Shrank|Spun|Won|Lost|Led|Laid|Lay|Lit|Bit|Hid|Held|Heard|Meant|Paid|Sold|Told|Understood|Sought','Sought'),
 p('romance-languages','Language','Name a Romance language.','Languages descended from Latin; a curated list including regional languages, not dialect names that are treated as aliases.','https://www.britannica.com/topic/Romance-languages','French|Spanish^Castilian|Italian|Portuguese|Romanian|Catalan^Valencian|Occitan^Provençal|Sardinian|Corsican|Galician|Asturian^Asturleonese|Aragonese|Romansh|Friulian|Ladin|Sicilian|Neapolitan|Venetian|Lombard|Piedmontese|Ligurian|Emilian|Romagnol|Walloon|Aromanian|Megleno-Romanian^Megleno Romanian|Istro-Romanian^Istro Romanian|Dalmatian','Dalmatian'),
 p('shakespeare','Film & books','Name a play by William Shakespeare.','The 38 plays listed by the Royal Shakespeare Company, including The Two Noble Kinsmen. Poems do not count.','https://www.rsc.org.uk/shakespeares-plays','Hamlet|Macbeth|Romeo and Juliet|Othello|King Lear|A Midsummer Night’s Dream^A Midsummer Nights Dream^Midsummer Nights Dream|The Tempest^Tempest|Much Ado About Nothing|Twelfth Night|The Merchant of Venice^Merchant of Venice|As You Like It|Julius Caesar|Richard III^Richard 3|Richard II^Richard 2|Henry V^Henry 5|Henry IV Part 1^Henry 4 Part 1|Henry IV Part 2^Henry 4 Part 2|Henry VI Part 1^Henry 6 Part 1|Henry VI Part 2^Henry 6 Part 2|Henry VI Part 3^Henry 6 Part 3|Henry VIII^Henry 8|King John|The Taming of the Shrew^Taming of the Shrew|The Comedy of Errors^Comedy of Errors|The Winter’s Tale^Winters Tale|Measure for Measure|All’s Well That Ends Well^Alls Well That Ends Well|Love’s Labour’s Lost^Loves Labours Lost^Loves Labors Lost|The Merry Wives of Windsor^Merry Wives of Windsor|Antony and Cleopatra|Coriolanus|Titus Andronicus|Troilus and Cressida|Timon of Athens|Pericles|Cymbeline|The Two Gentlemen of Verona^Two Gentlemen of Verona|The Two Noble Kinsmen^Two Noble Kinsmen','The Two Noble Kinsmen'),
 p('austen','Film & books','Name one of Jane Austen’s six completed novels.','The six published complete novels; unfinished works and juvenilia are excluded.','https://janeaustens.house/jane-austen/novels/','Pride and Prejudice|Sense and Sensibility|Emma|Persuasion|Mansfield Park|Northanger Abbey','Northanger Abbey'),
 p('bond-films','Film & books','Name an Eon-produced James Bond film released by 2021.','The 25 official Eon films through No Time to Die; Casino Royale (1967) and Never Say Never Again are excluded.','https://www.007.com/the-films/','Goldfinger|Skyfall|Casino Royale|No Time to Die|GoldenEye|Spectre|Dr. No^Doctor No|From Russia with Love|Thunderball|You Only Live Twice|On Her Majesty’s Secret Service^On Her Majestys Secret Service|Diamonds Are Forever|Live and Let Die|The Man with the Golden Gun|The Spy Who Loved Me|Moonraker|For Your Eyes Only|Octopussy|A View to a Kill|The Living Daylights|Licence to Kill^License to Kill|Tomorrow Never Dies|The World Is Not Enough|Die Another Day|Quantum of Solace','On Her Majesty’s Secret Service'),
 p('pixar-features','Film & books','Name a Pixar feature released by the end of 2024.','Feature films through Inside Out 2; shorts and later releases excluded.','https://www.pixar.com/feature-films','Toy Story|Finding Nemo|The Incredibles^Incredibles|Monsters, Inc.^Monsters Inc|Cars|WALL-E^Walle|Up|Ratatouille|Inside Out|Coco|Brave|Toy Story 2|Toy Story 3|Toy Story 4|Finding Dory|Cars 2|Cars 3|Monsters University|Incredibles 2|The Good Dinosaur^Good Dinosaur|A Bug’s Life^A Bugs Life^Bugs Life|Onward|Soul|Luca|Turning Red|Lightyear|Elemental|Inside Out 2','The Good Dinosaur'),
 p('instrument','Culture','Name a musical instrument.','Individual instruments, not generic families or brands. The curated list does not include every instrument.','https://www.metmuseum.org/departments/musical-instruments','Piano|Guitar|Violin|Drum^Drums|Flute|Trumpet|Clarinet|Saxophone|Cello|Double bass|Viola|Harp|Oboe|Bassoon|Trombone|French horn^Horn|Tuba|Recorder|Ukulele|Banjo|Mandolin|Accordion|Harmonica|Organ|Xylophone|Marimba|Glockenspiel|Vibraphone|Timpani^Kettledrum|Tambourine|Triangle|Cymbal^Cymbals|Bongo^Bongos|Conga^Congas|Djembe|Sitar|Tabla|Sarod|Erhu|Pipa|Koto|Shamisen|Shakuhachi|Bagpipes|Dulcimer|Zither|Lute|Theorbo|Oud|Balalaika|Bandoneon|Concertina|Theremin|Celesta|Cor anglais^English horn|Contrabassoon|Bass clarinet|Piccolo|Clavichord|Harpsichord|Nyckelharpa','Nyckelharpa'),
 p('greek-gods','Culture','Name a deity from Greek mythology.','Greek names, not Roman-only equivalents. A curated list of gods and goddesses; heroes are excluded.','https://www.theoi.com/','Zeus|Hera|Poseidon|Athena|Apollo|Artemis|Ares|Aphrodite|Hermes|Hephaestus|Demeter|Hestia|Dionysus|Hades|Persephone|Hecate|Eros|Pan|Iris|Nike|Nemesis|Tyche|Hypnos|Thanatos|Morpheus|Helios|Selene|Eos|Gaia|Uranus^Ouranos|Cronus^Kronos|Rhea|Oceanus^Okeanos|Tethys|Themis|Mnemosyne|Leto|Asclepius|Hebe|Triton|Amphitrite|Proteus|Nereus|Phobos|Deimos|Eris|Enyo|Harmonia|Hygieia|Melinoe','Melinoe'),
 p('roman-gods','Culture','Name a deity worshipped in ancient Rome.','Roman names; Greek-only names and mortal emperors excluded from this curated list.','https://www.britannica.com/topic/Roman-religion','Jupiter|Juno|Neptune|Venus|Mars|Mercury|Minerva|Diana|Apollo|Vulcan|Vesta|Ceres|Bacchus|Pluto|Proserpina|Saturn|Janus|Fortuna|Victoria|Cupid|Bellona|Flora|Faunus|Pomona|Vertumnus|Terminus|Quirinus|Ops|Consus|Portunus|Fides|Concordia|Pax|Salus|Sol|Luna|Aurora|Juventas|Liber|Libera','Portunus'),
 p('chess-pieces','Sport','Name a type of chess piece.','The six types in standard chess. Fairy-chess pieces excluded.','https://handbook.fide.com/chapter/E012023','King|Queen|Rook^Castle|Bishop|Knight|Pawn','Knight'),
 p('olympic-paris','Sport','Name a sport on the Paris 2024 Olympic programme.','Sport names, not individual event distances. Aquatic disciplines are accepted as aliases of aquatics.','https://olympics.com/en/olympic-games/paris-2024/sports','Athletics^Track and field|Football^Soccer|Basketball^3x3 basketball|Tennis|Swimming^Aquatics^Diving^Artistic swimming^Water polo|Gymnastics^Artistic gymnastics^Rhythmic gymnastics^Trampoline|Cycling^Road cycling^Track cycling^BMX^Mountain biking|Volleyball^Beach volleyball|Badminton|Table tennis^Ping pong|Boxing|Judo|Wrestling|Fencing|Archery|Shooting|Rowing|Canoe^Canoeing^Canoe sprint^Canoe slalom|Sailing|Surfing|Skateboarding|Sport climbing^Climbing|Golf|Rugby sevens^Rugby|Hockey^Field hockey|Handball|Triathlon|Modern pentathlon|Taekwondo|Weightlifting|Equestrian^Horse riding|Breaking^Breakdancing','Breaking'),
 p('athletics-events','Sport','Name an athletics event held at Paris 2024.','Event names; men’s and women’s versions count as the same answer. Distances may be written with or without spaces.','https://worldathletics.org/competitions/olympic-games/paris24','100 metres^100m^100 meters|200 metres^200m^200 meters|400 metres^400m^400 meters|800 metres^800m^800 meters|1500 metres^1500m^1500 meters|5000 metres^5000m^5000 meters|10000 metres^10000m^10000 meters|Marathon|High jump|Long jump|Triple jump|Pole vault|Shot put|Discus throw^Discus|Hammer throw^Hammer|Javelin throw^Javelin|100 metres hurdles^100m hurdles^100 meters hurdles|110 metres hurdles^110m hurdles^110 meters hurdles|400 metres hurdles^400m hurdles^400 meters hurdles|3000 metres steeplechase^3000m steeplechase^Steeplechase|4x100 metres relay^4x100m relay^4x100 relay|4x400 metres relay^4x400m relay^4x400 relay|20 kilometre race walk^20km race walk^20km walk|Marathon race walk mixed relay^Mixed race walk relay|Decathlon|Heptathlon','Marathon race walk mixed relay'),
 p('world-cup-winners','Sport','Name a country that won the men’s FIFA World Cup by 2022.','Winning national teams from 1930 through 2022. West Germany is accepted as Germany.','https://www.fifa.com/en/tournaments/mens/worldcup','Brazil|Germany^West Germany|Argentina|France|Italy|England|Spain|Uruguay','Uruguay'),
];
export const bank:Prompt[]=[...legacy.map(expandLegacy),...everydayFood,...everydayAnimals,...everydayHome,...everydayGeography,...everydayScience,...everydayTechnology,...everydayTransport,...everydayGeneral,...everydayEntertainment,...everydayExtra,...everydaySport].map(reviewPrompt);
