import {p} from './content-builder';
export const geography=[
 p('eu-2024','Geography','Name a European Union member country as of December 2024.','The 27 member states at that fixed date; the United Kingdom is excluded.','https://european-union.europa.eu/principles-countries-history/eu-countries_en','France|Germany|Italy|Spain|Portugal|Ireland|Netherlands^Holland|Belgium|Austria|Sweden|Denmark|Finland|Greece|Poland|Czechia^Czech Republic|Hungary|Romania|Bulgaria|Croatia|Slovakia|Slovenia|Estonia|Latvia|Lithuania|Luxembourg|Cyprus|Malta','Malta'),
 p('nato-2024','Geography','Name a NATO member country as of December 2024.','The 32 members after Sweden joined in March 2024; membership is pinned to this date.','https://www.nato.int/cps/en/natohq/nato_countries.htm','United States^USA^US|United Kingdom^UK^Britain|Canada|France|Germany|Italy|Spain|Portugal|Netherlands^Holland|Belgium|Denmark|Norway|Iceland|Greece|Türkiye^Turkey|Poland|Hungary|Czechia^Czech Republic|Bulgaria|Romania|Slovakia|Slovenia|Estonia|Latvia|Lithuania|Albania|Croatia|Montenegro|North Macedonia|Finland|Sweden|Luxembourg','Luxembourg'),
 p('state-capitals','Geography','Name a US state capital.','The capitals of the 50 states; Washington DC is excluded.','https://www.usa.gov/states-and-territories','Austin|Boston|Denver|Phoenix|Atlanta|Honolulu|Sacramento|Tallahassee|Albany|Olympia|Salem|Carson City|Salt Lake City|Santa Fe|Oklahoma City|Topeka|Lincoln|Des Moines|Springfield|Indianapolis|Columbus|Lansing|Madison|Saint Paul^St Paul|Jefferson City|Little Rock|Baton Rouge|Jackson|Montgomery|Nashville|Frankfort|Charleston|Richmond|Raleigh|Columbia|Annapolis|Dover|Harrisburg|Trenton|Hartford|Providence|Concord|Montpelier|Augusta|Pierre|Bismarck|Helena|Cheyenne|Boise|Juneau','Montpelier'),
 p('english-counties','Geography','Name a ceremonial county of England.','The 48 lieutenancy areas, not historic counties or individual council areas.','https://www.legislation.gov.uk/ukpga/1997/23/schedule/1','Cornwall|Devon|Dorset|Somerset|Wiltshire|Hampshire|Kent|Surrey|East Sussex|West Sussex|Essex|Suffolk|Norfolk|Cambridgeshire|Lincolnshire|Nottinghamshire|Derbyshire|Leicestershire|Northamptonshire|Rutland|Bedfordshire|Hertfordshire|Buckinghamshire|Oxfordshire|Berkshire|Gloucestershire|Herefordshire|Worcestershire|Warwickshire|West Midlands|Staffordshire|Shropshire|Cheshire|Greater Manchester|Merseyside|Lancashire|Cumbria|Northumberland|Tyne and Wear|County Durham^Durham|North Yorkshire|West Yorkshire|South Yorkshire|East Riding of Yorkshire^East Riding|Greater London|City of London|Isle of Wight|Bristol','Rutland'),
 p('canada-divisions','Geography','Name a Canadian province or territory.','The ten provinces and three territories; cities are excluded.','https://www.canada.ca/en/intergovernmental-affairs/services/provinces-territories.html','Ontario|Quebec^Québec|British Columbia^BC|Alberta|Manitoba|Saskatchewan|Nova Scotia|New Brunswick|Newfoundland and Labrador^Newfoundland|Prince Edward Island^PEI|Yukon|Northwest Territories^NWT|Nunavut','Nunavut'),
 p('australia-divisions','Geography','Name an Australian state or mainland internal territory.','Six states, the Northern Territory and Australian Capital Territory; external territories and Jervis Bay excluded.','https://www.australia.gov.au/states','New South Wales^NSW|Victoria^VIC|Queensland^QLD|Western Australia^WA|South Australia^SA|Tasmania^TAS|Northern Territory^NT|Australian Capital Territory^ACT','Australian Capital Territory'),
 p('african-capitals','Geography','Name a capital of an African UN member country.','National capitals, including South Africa’s three and Eswatini’s two; spelling aliases are curated.','https://www.britannica.com/topic/list-of-national-capitals-2026932','Cairo|Nairobi|Accra|Abuja|Rabat|Tunis|Algiers|Addis Ababa|Pretoria|Cape Town|Bloemfontein|Dakar|Kampala|Kigali|Harare|Lusaka|Luanda|Maputo|Windhoek|Gaborone|Maseru|Mbabane|Lobamba|Lilongwe|Dodoma|Juba|Khartoum|Tripoli|Nouakchott|Bamako|Niamey|N’Djamena^Ndjamena|Ouagadougou|Porto-Novo|Lomé^Lome|Yamoussoukro|Monrovia|Freetown|Conakry|Bissau|Banjul|Praia|São Tomé^Sao Tome|Malabo|Libreville|Brazzaville|Kinshasa|Bangui|Gitega|Mogadishu|Djibouti|Asmara|Antananarivo|Moroni|Port Louis|Victoria','Gitega'),
 p('asian-capitals','Geography','Name a capital of an Asian UN member country.','UN M49 region; includes political and administrative capitals where countries distinguish them. Disputed status is not a sovereignty claim.','https://www.britannica.com/topic/list-of-national-capitals-2026932','Tokyo|Beijing|New Delhi^Delhi|Bangkok|Hanoi|Seoul|Pyongyang|Singapore|Kuala Lumpur|Putrajaya|Jakarta|Manila|Dhaka|Islamabad|Kathmandu|Thimphu|Malé^Male|Colombo|Sri Jayawardenepura Kotte^Kotte|Ulaanbaatar^Ulan Bator|Phnom Penh|Vientiane|Naypyidaw^Nay Pyi Taw|Bandar Seri Begawan|Dili|Astana|Tashkent|Bishkek|Dushanbe|Ashgabat|Kabul|Tehran|Baghdad|Riyadh|Abu Dhabi|Muscat|Sana’a^Sanaa|Doha|Manama|Kuwait City|Amman|Jerusalem|Beirut|Damascus|Ankara|Nicosia|Yerevan|Baku|Tbilisi','Sri Jayawardenepura Kotte'),
 p('european-capitals','Geography','Name a capital of a European UN member country.','UN M49 Europe. National capitals only; Amsterdam is accepted, The Hague is not the constitutional capital.','https://www.britannica.com/topic/list-of-national-capitals-2026932','London|Paris|Berlin|Rome|Madrid|Lisbon|Dublin|Amsterdam|Brussels|Vienna|Bern^Berne|Stockholm|Oslo|Copenhagen|Helsinki|Reykjavík^Reykjavik|Athens|Warsaw|Prague|Bratislava|Budapest|Bucharest|Sofia|Zagreb|Ljubljana|Belgrade|Podgorica|Sarajevo|Skopje|Tirana|Tallinn|Riga|Vilnius|Minsk|Kyiv^Kiev|Moscow|Chișinău^Chisinau|Valletta|Luxembourg|Andorra la Vella|Monaco|Vaduz|San Marino','Andorra la Vella'),
 p('med-islands','Geography','Name an island in the Mediterranean Sea.','Includes Adriatic and Aegean islands; excludes Atlantic and Black Sea islands. Curated, non-exhaustive set.','https://www.britannica.com/place/Mediterranean-Sea','Sicily|Sardinia|Corsica|Cyprus|Crete|Malta|Gozo|Comino|Majorca^Mallorca|Menorca^Minorca|Ibiza|Formentera|Elba|Capri|Ischia|Procida|Lipari|Stromboli|Vulcano|Salina|Pantelleria|Lampedusa|Corfu^Kerkyra|Rhodes|Kos|Santorini^Thira|Mykonos|Naxos|Paros|Lesbos^Lesvos|Chios|Samos|Lemnos^Limnos|Samothrace^Samothraki|Thasos|Euboea^Evia|Zakynthos^Zante|Kefalonia^Cephalonia|Ithaca^Ithaki|Lefkada|Hvar|Brač^Brac|Korčula^Korcula|Vis|Krk|Cres|Lošinj^Losinj|Pag|Djerba|Kerkennah','Samothrace'),
];
