import {q,refs as r} from './content-everyday-builder';
export const everydayTransport=[
q('vehicles','Transport','easy','Name a vehicle.',r.transport,'Car|Bus|Train|Bicycle^Bike|Motorcycle^Motorbike|Lorry^Truck|Van|Taxi|Boat|Aeroplane^Airplane;Tram|Coach|Minibus|Scooter|Moped|Tractor|Ambulance|Fire engine|Police car|Ferry|Ship|Helicopter|Glider^Sailplane|Hot-air balloon|Submarine|Hovercraft|Cable car|Monorail|Rickshaw|Tuk-tuk;Skateboard|Roller skates|Wheelchair|Mobility scooter|Golf cart|Snowmobile|Jet ski|Quad bike|Forklift|Bulldozer|Excavator|Tank|Sleigh|Sledge|Canoe|Kayak|Yacht|Raft;Funicular;Hydrofoil','broad','Vehicles carrying people or goods; broad types and named types both count.'),
q('car-parts','Transport','easy','Name a part of a car.',r.words,'Wheel|Tyre^Tire|Engine|Door|Window|Steering wheel|Seat|Brake|Headlight|Mirror;Bonnet^Hood|Boot^Trunk|Bumper|Windscreen^Windshield|Wiper|Dashboard|Seatbelt|Gearbox^Transmission|Clutch|Accelerator|Pedal|Exhaust|Battery|Radiator|Alternator|Starter motor|Spark plug|Piston|Cylinder|Axle;Suspension|Shock absorber|Catalytic converter|Fuel tank|Fuel injector|Carburettor^Carburetor|Air filter|Oil filter|Camshaft|Crankshaft|Timing belt|Differential|Handbrake|Indicator|Airbag|Horn|Number plate;Flywheel;Turbocharger','broad','Car components, not brand names; electric and combustion components both count.'),
q('bicycle-parts','Transport','easy','Name a part of a bicycle.',r.words,'Wheel|Tyre^Tire|Frame|Handlebar|Saddle|Pedal|Chain|Brake|Bell|Spoke;Rim|Inner tube|Valve|Hub|Crank|Chainring|Sprocket|Gear|Derailleur|Fork|Headset|Stem|Seatpost|Seat tube|Top tube|Down tube|Head tube|Chainstay|Seatstay|Mudguard|Pannier rack|Reflector|Light|Bottle cage;Cable|Brake lever|Shifter|Cassette|Freewheel|Bottom bracket|Quick release|Disc rotor|Brake pad;Dropout;Bar-end plug','broad','Bicycle components; clothing and helmets are excluded.'),
q('london-tube-lines','Transport','easy','Name a London Underground line.','https://tfl.gov.uk/maps/track/tube','Central|Northern|Piccadilly|Victoria|District|Circle;Bakerloo|Jubilee|Metropolitan;Hammersmith and City^Hammersmith & City;;Waterloo and City^Waterloo & City','complete','The eleven Underground lines; Elizabeth line, DLR and Overground are separate systems.'),
q('car-brands','Transport','easy','Name a car brand.',r.transport,'Ford|Toyota|Volkswagen^VW|BMW|Mercedes-Benz^Mercedes|Audi|Vauxhall|Nissan|Honda|Tesla;Hyundai|Kia|Peugeot|Renault|Citroën^Citroen|Fiat|Volvo|Skoda|SEAT|Mazda|Suzuki|Subaru|Mitsubishi|Lexus|Jaguar|Land Rover|Mini|Porsche|Ferrari|Lamborghini|Bentley|Rolls-Royce|Aston Martin|Alfa Romeo;Dacia|Saab|Opel|Chevrolet|Cadillac|Buick|Dodge|Chrysler|Jeep|GMC|Lincoln|Infiniti|Acura|Genesis|McLaren|Bugatti|Maserati|Lotus|Morgan|MG|BYD|Polestar|Rivian|Lucid|Lancia;Daihatsu;Koenigsegg','broad','Current and historic marques, not individual models.'),
q('boat-types','Transport','easy','Name a type of boat or ship.',r.transport,'Yacht|Ferry|Canoe|Kayak|Rowing boat|Speedboat|Cruise ship|Cargo ship|Fishing boat|Submarine;Tugboat|Lifeboat|Sailboat|Dinghy|Catamaran|Barge|Narrowboat|Houseboat|Raft|Hovercraft|Hydrofoil|Tanker|Container ship|Bulk carrier|Destroyer|Frigate|Corvette|Aircraft carrier|Battleship|Galleon;Schooner|Brig|Sloop|Ketch|Yawl|Clipper|Dhow|Junk|Gondola|Coracle|Longship|Trimaran|Punt|Wherry;Felucca;Xebec','broad','Watercraft types, including warships and traditional craft; named individual ships are excluded.'),
q('aircraft-types','Transport','easy','Name a type of aircraft.',r.transport,'Aeroplane^Airplane|Helicopter|Glider^Sailplane|Hot-air balloon|Jet|Airliner|Biplane|Drone;Seaplane|Floatplane|Flying boat|Fighter|Bomber|Transport aircraft|Cargo aircraft|Light aircraft|Business jet|Turboprop|Airship|Zeppelin|Blimp|Gyroplane^Autogyro|Hang glider|Paraglider|Ultralight|Microlight|Monoplane|Triplane|Tiltrotor;Amphibious aircraft|Rocket plane|Supersonic aircraft|Canard aircraft|Flying wing|Rotorcraft|Ornithopter|Air ambulance;Gyrodyne;Motor glider','broad','Aircraft categories and established configurations; spacecraft are excluded.'),
q('road-sign-shapes','Transport','easy','Name a common UK road-sign shape.','https://www.gov.uk/guidance/the-highway-code/traffic-signs','Circle^Circular|Triangle^Triangular|Rectangle^Rectangular;Square;;;Octagon^Octagonal','complete','Standard signs include the octagonal STOP sign; pentagonal route shields are not UK regulatory signs.'),
q('traffic-light-colours','Transport','easy','Name a UK traffic-light colour.','https://www.gov.uk/guidance/the-highway-code/light-signals-controlling-traffic','Red|Green;;;Amber^Yellow','complete','The three colours, not combinations such as red and amber.'),
q('uk-driving-licence-categories','Transport','medium','Name a UK driving licence category.','https://www.gov.uk/driving-licence-categories','B|A|AM;A1|A2|B1|C|C1|D|D1;BE|C1E|CE|D1E|DE;F|G|H|K;Q','complete','Current lettered categories, including special vehicles; legacy entitlement codes are excluded.'),
q('london-airports','Transport','easy','Name a major airport serving London.','https://www.visitlondon.com/traveller-information/travel-to-london/airport','Heathrow|Gatwick|Stansted|Luton;London City^City airport;;;Southend','complete','The six airports conventionally marketed as serving London.'),
q('nautical-directions','Transport','medium','Name a direction or position aboard a vessel.','https://www.britannica.com/technology/ship','Port|Starboard|Bow|Stern;Fore^Forward|Aft|Amidships|Abeam|Aloft;Athwartships|Inboard|Outboard|Windward|Leeward;Astern;Ahead','complete','Established nautical relative-position vocabulary, not compass bearings.'),
q('rail-gauges','Transport','medium','Name a commonly used railway gauge.','https://www.britannica.com/technology/railroad','Standard gauge^1435 mm|Metre gauge^Meter gauge^1000 mm|Broad gauge|Narrow gauge;Russian gauge^1520 mm|Indian gauge^1676 mm|Iberian gauge^1668 mm;Cape gauge^1067 mm|Irish gauge^1600 mm;Three-foot gauge^914 mm;Bosnian gauge^760 mm','complete','Common named gauges and the broad/narrow umbrella classes; not every historic local gauge.'),
q('train-types','Transport','medium','Name a type of railway train.',r.transport,'Steam train|Diesel train|Electric train|Passenger train|Freight train^Goods train|High-speed train|Sleeper train|Commuter train;Express train|Local train|Intercity train|Regional train|Metro train|Underground train|Light rail train|Monorail|Maglev|Tilting train|Bullet train|Container train|Coal train|Oil train|Mail train|Excursion train|Heritage train|Tourist train|Hospital train|Armoured train|Maintenance train;Multiple unit|Electric multiple unit^EMU|Diesel multiple unit^DMU|Push-pull train|Rack railway train|Funicular|Autotrain|Railcar;Mixed train;Roadrailer','broad','Types by power, service or construction; individual train names are excluded.'),
];
