import {p} from './content-builder';
export const language=[
 p('prepositions','Language','Name an English preposition.','Single-word or established multi-word prepositions; a curated list, not an exhaustive dictionary.','https://dictionary.cambridge.org/grammar/british-grammar/prepositions','In|On|At|By|To|For|From|With|Without|About|Above|Below|Under|Over|Between|Among|Before|After|During|Through|Across|Along|Around|Behind|Beside|Beyond|Beneath|Inside|Outside|Into|Onto|Upon|Within|Against|Towards^Toward|Off|Of|Near|Past|Since|Until|Till|Despite|Except|Concerning|Regarding|Via|Per|Versus|According to|Because of|In front of|Instead of|On behalf of|Owing to','Owing to'),
 p('conjunctions','Language','Name an English conjunction or conjunctive phrase.','Words or phrases joining clauses. Includes correlative pairs and subordinating conjunctions; curated list.','https://dictionary.cambridge.org/grammar/british-grammar/conjunctions','And|But|Or|So|Yet|Nor|For|Because|Although|Though|Even though|Since|As|If|Unless|While|Whereas|When|Whenever|Before|After|Until|Once|Whether|That|Provided that|Providing that|As long as|So long as|In case|Even if|Only if|As soon as|No sooner than|Rather than|As if|As though|Lest|Both and^Both… and|Either or^Either… or|Neither nor^Neither… nor|Not only but also','Lest'),
 p('germanic-languages','Language','Name a Germanic language.','Established languages, including historical languages; not all regional varieties are separately accepted. Curated list.','https://www.britannica.com/topic/Germanic-languages','English|German|Dutch|Afrikaans|Swedish|Danish|Norwegian|Icelandic|Faroese|Yiddish|Frisian^West Frisian|North Frisian|Saterland Frisian|Scots|Luxembourgish|Low German|Gothic|Old English|Old Norse|Old High German|Middle English|Middle High German|Norn|Lombardic|Vandalic','Norn'),
 p('slavic-languages','Language','Name a Slavic language.','Established modern or historical languages; standard languages and selected regional languages accepted.','https://www.britannica.com/topic/Slavic-languages','Russian|Polish|Ukrainian|Czech|Slovak|Bulgarian|Serbian|Croatian|Bosnian|Slovene^Slovenian|Macedonian|Belarusian|Upper Sorbian|Lower Sorbian|Kashubian|Rusyn|Old Church Slavonic^Old Church Slavic|Church Slavonic|Polabian','Kashubian'),
 p('indo-aryan','Language','Name an Indo-Aryan language.','Language names within the Indo-Aryan branch, including historical languages. Curated non-exhaustive list.','https://www.britannica.com/topic/Indo-Aryan-languages','Hindi|Urdu|Bengali^Bangla|Punjabi^Panjabi|Gujarati|Marathi|Nepali|Sinhala^Sinhalese|Assamese|Odia^Oriya|Sindhi|Kashmiri|Konkani|Sanskrit|Pali|Prakrit|Maithili|Bhojpuri|Magahi|Awadhi|Braj|Rajasthani|Marwari|Dogri|Saraiki|Haryanvi|Chhattisgarhi|Kumaoni|Garhwali|Romani|Dhivehi^Maldivian|Shina|Khowar|Kalasha|Bishnupriya Manipuri','Kalasha'),
 p('punctuation','Language','Name a punctuation mark used in English writing.','Names, not typed symbols; singular and selected plural aliases accepted. Includes typographic punctuation.','https://dictionary.cambridge.org/grammar/british-grammar/punctuation','Full stop^Period|Comma|Question mark|Exclamation mark^Exclamation point|Colon|Semicolon^Semi colon|Apostrophe|Hyphen|Dash|En dash|Em dash|Ellipsis|Quotation mark^Quotation marks^Quote mark^Inverted commas|Bracket^Brackets|Parenthesis^Parentheses|Square bracket^Square brackets|Curly bracket^Curly brackets^Brace|Slash^Forward slash|Backslash|Asterisk|Bullet|Interrobang','Interrobang'),
 p('rhetorical-devices','Language','Name a rhetorical or literary device.','Named devices of style or persuasion; a curated non-exhaustive list. Definitions can overlap across traditions.','https://www.poetryfoundation.org/learn/glossary-terms','Metaphor|Simile|Alliteration|Assonance|Consonance|Onomatopoeia|Hyperbole|Irony|Personification|Oxymoron|Paradox|Pun|Anaphora|Epistrophe|Antithesis|Chiasmus|Metonymy|Synecdoche|Litotes|Euphemism|Apostrophe|Rhetorical question|Asyndeton|Polysyndeton|Zeugma|Syllogism|Anadiplosis|Epizeuxis|Anastrophe|Aposiopesis|Antanaclasis|Hypophora|Prolepsis|Parataxis|Enjambment|Caesura|Allegory|Allusion|Symbolism|Foreshadowing|Synaesthesia^Synesthesia|Hendiadys','Hendiadys'),
 p('literary-genres','Language','Name a literary genre or established subgenre.','Fiction, poetry or nonfiction genres; arbitrary topics and named book titles excluded. Curated list.','https://www.britannica.com/art/literature','Fantasy|Science fiction^Sci fi|Romance|Mystery|Crime fiction|Horror|Thriller|Historical fiction|Adventure|Comedy|Tragedy|Satire|Fable|Fairy tale|Myth|Legend|Epic|Lyric poetry|Elegy|Ode|Pastoral|Memoir|Biography|Autobiography|Essay|Travel writing|Literary fiction|Gothic fiction|Magical realism|Dystopia^Dystopian fiction|Utopia^Utopian fiction|Bildungsroman|Picaresque|Epistolary novel|Detective fiction|Noir|Western|Cyberpunk|Steampunk|Space opera|Urban fantasy|High fantasy|Low fantasy|Dark fantasy|Speculative fiction|Creative nonfiction','Picaresque'),
 p('classical-plurals','Language','Give a classical-origin plural used in English.','Plural forms borrowed from Latin or Greek; regular English alternatives are not accepted for this question. Curated list.','https://dictionary.cambridge.org/grammar/british-grammar/nouns-countable-and-uncountable','Criteria|Phenomena|Data|Bacteria|Alumni|Alumnae|Cacti|Fungi|Nuclei|Syllabi|Radii|Stimuli|Analyses|Diagnoses|Hypotheses|Theses|Crises|Parentheses|Ellipses|Axes|Appendices|Indices|Matrices|Vertices|Vortices|Formulae|Larvae|Antennae|Vertebrae|Nebulae|Curricula|Memoranda|Media|Strata|Errata|Ova|Genera|Species|Corpora','Corpora'),
 p('homophones','Language','Name an English word with a different-spelling homophone.','One word, not a pair. Standard British pronunciation; this curated list accepts both sides of each listed pair.','https://dictionary.cambridge.org/','Sea^See|Blue^Blew|New^Knew|Night^Knight|Right^Write^Rite|Red^Read|Son^Sun|Flower^Flour|Pair^Pear^Pare|Bear^Bare|Brake^Break|Peace^Piece|Meet^Meat|Week^Weak|Whole^Hole|Mail^Male|Sale^Sail|Tail^Tale|Wait^Weight|Waist^Waste|Deer^Dear|Here^Hear|Their^There^They’re|To^Too^Two|One^Won|Wood^Would|Weather^Whether|Steal^Steel|Plain^Plane|Principal^Principle|Stationary^Stationery|Allowed^Aloud|Profit^Prophet|Aisle^Isle|Board^Bored|Cell^Sell|Sole^Soul|Role^Roll|Vain^Vein^Vane|Flew^Flu^Flue|Cereal^Serial|Complement^Compliment|Council^Counsel|Leek^Leak|Course^Coarse|Foul^Fowl|Grate^Great|Forth^Fourth|Gait^Gate|Hoard^Horde|Pore^Pour^Poor|Yew^You^Ewe','Yew'),
];
