import {randomBytes,createHash} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {transaction} from './database';
import {matchAnswer,suggestAnswer,selectPrompts,phase,eligiblePrompts,parseDifficulty,parseTopics} from '../src/shared/core';
import {CATEGORIES,POINTS,SCORING_VERSION,type DifficultyMode,type Prompt,type Outcome,type RunView,type Category} from '../src/shared/types';
export class GameError extends Error{constructor(public status:number,message:string){super(message);}}
const id=()=>randomBytes(24).toString('base64url');
type Row=Record<string,any>;
export class Game {
 constructor(public db:DatabaseSync,public bank:Prompt[],public clock:()=>number=Date.now,public readingMs=3000,public answerMs=25000){if(!bank.length)throw new Error('No reviewed content');db.prepare('INSERT OR IGNORE INTO content_versions VALUES(?,?,?)').run('bank-v1-'+createHash('sha256').update(JSON.stringify(bank)).digest('hex').slice(0,16),JSON.stringify(bank),clock());}
 scoring(runId:string){const participant=this.one('SELECT challenge_id FROM participants WHERE run_id=?',runId);return participant?JSON.parse(this.one('SELECT rules FROM challenges WHERE id=?',participant.challenge_id)!.rules).points??POINTS:POINTS;}
 one(sql:string,...args:any[]):Row|undefined{return this.db.prepare(sql).get(...args) as Row|undefined;}
 all(sql:string,...args:any[]):Row[]{return this.db.prepare(sql).all(...args) as Row[];}
 write(sql:string,...args:any[]){return this.db.prepare(sql).run(...args);}
 owned(runId:string,session:string):Row {const r=this.one('SELECT * FROM runs WHERE id=? AND session_id=?',runId,session);if(!r)throw new GameError(404,'This dive belongs to another browser, or no longer exists. Start a new dive.');const p=this.one('SELECT challenge_id FROM participants WHERE run_id=?',runId);if(p)this.challenge(p.challenge_id);return r;}
 eligible(categories:Category[],difficulty:DifficultyMode='mixed'){return eligiblePrompts(this.bank,categories,difficulty);}
 categories(raw:unknown):Category[]{try{return parseTopics(raw);}catch(e){throw new GameError(400,(e as Error).message);}}
 difficulty(raw:unknown):DifficultyMode{try{return parseDifficulty(raw);}catch(e){throw new GameError(400,(e as Error).message);}}
 newRun(session:string,mode:'solo'|'endless'|'challenge',relaxed:boolean,categories:Category[],recent:string[]=[],snapshot?:Prompt[],difficulty:DifficultyMode='easy',scoringVersion=SCORING_VERSION):string{let picked;try{picked=snapshot?{prompts:snapshot,cycled:false}:selectPrompts(this.eligible(categories,difficulty),7,recent,Math.random,difficulty);}catch(e){throw new GameError(400,(e as Error).message);}const runId=id();this.write('INSERT INTO runs(id,session_id,mode,relaxed,snapshot,categories,recent,cycled,created,difficulty,scoring_version) VALUES(?,?,?,?,?,?,?,?,?,?,?)',runId,session,mode,relaxed?1:0,JSON.stringify(picked.prompts),JSON.stringify(categories),JSON.stringify(recent),picked.cycled?1:0,this.clock(),difficulty,scoringVersion);return runId;}
 createRun(session:string,raw:Row){if(raw.mode!==undefined&&!['solo','endless'].includes(raw.mode))throw new GameError(400,'Unknown dive format.');const recent=Array.isArray(raw.recent)?raw.recent.filter((v:unknown)=>typeof v==='string').slice(-500):[];return this.newRun(session,raw.mode??'solo',raw.relaxed===true,this.categories(raw.categories),recent,undefined,this.difficulty(raw.difficulty));}
 begin(runId:string,session:string):RunView{return transaction(this.db,()=>{const r=this.owned(runId,session);if(r.complete)return this.view(r);const rounds=this.all('SELECT * FROM rounds WHERE run_id=? ORDER BY round_index',runId);const previous=rounds.at(-1);if(previous&&!previous.outcome)return this.view(r);const index=rounds.length;let snapshot:Prompt[]=JSON.parse(r.snapshot);if(index>=snapshot.length){if(r.mode!=='endless'){this.finish(runId);return this.view({...r,complete:1});}const recent=[...JSON.parse(r.recent),...snapshot.map(p=>p.id)];const eligible=this.eligible(JSON.parse(r.categories),r.difficulty??'mixed');const picked=selectPrompts(eligible,7,recent,Math.random,r.difficulty??'mixed');snapshot.push(...picked.prompts);r.snapshot=JSON.stringify(snapshot);r.recent=JSON.stringify(recent.slice(-eligible.length));r.cycled=picked.cycled?1:0;this.write('UPDATE runs SET snapshot=?,recent=?,cycled=? WHERE id=?',r.snapshot,r.recent,r.cycled,runId);}
 const participant=this.one('SELECT challenge_id FROM participants WHERE run_id=?',runId);const rules=participant?JSON.parse(this.challenge(participant.challenge_id).rules):{readingMs:this.readingMs,answerMs:this.answerMs};const now=this.clock();this.write('INSERT INTO rounds(run_id,round_index,start,reading_until,deadline) VALUES(?,?,?,?,?)',runId,index,now,now+rules.readingMs,r.relaxed?null:now+rules.readingMs+rules.answerMs);return this.view(r);});}
 finish(runId:string){this.write('UPDATE runs SET complete=1 WHERE id=?',runId);this.write('UPDATE participants SET completed=? WHERE run_id=?',this.clock(),runId);}
 commit(r:Row,round:Row,raw:string,status:'answer'|'timeout',submissionId:string,received:number,confirmed?:string){const prompt:Prompt=JSON.parse(r.snapshot)[round.round_index];const matched=status==='answer'?matchAnswer(prompt,confirmed??raw):null;const scoring=this.scoring(r.id);const outcome:Outcome={index:round.round_index,promptId:prompt.id,promptVersion:prompt.version,prompt:prompt.text,submitted:status==='timeout'?'':raw,canonical:matched?.canonical??null,tier:matched?.tier??null,points:matched?scoring[matched.tier]:0,status:status==='timeout'?'timeout':matched?'accepted':'invalid',explanation:status==='timeout'?'No answer was committed before the deadline.':matched?matched.explanation:'We couldn’t match that to this question’s answer list.'};this.write('UPDATE rounds SET submission_id=?,received=?,raw_input=?,outcome=? WHERE run_id=? AND round_index=? AND outcome IS NULL',submissionId,received,outcome.submitted,JSON.stringify(outcome),r.id,round.round_index);round.outcome=JSON.stringify(outcome);if(r.mode!=='endless'&&round.round_index===6){this.finish(r.id);r.complete=1;}}
 reconcile(r:Row){const round=this.one('SELECT * FROM rounds WHERE run_id=? ORDER BY round_index DESC LIMIT 1',r.id);if(round&&!round.outcome&&round.deadline!==null&&this.clock()>round.deadline+250)this.commit(r,round,'','timeout','timeout',this.clock());return round;}
 submit(runId:string,session:string,body:Row,received=this.clock()):RunView{return transaction(this.db,()=>{const r=this.owned(runId,session);const round=this.one('SELECT * FROM rounds WHERE run_id=? ORDER BY round_index DESC LIMIT 1',runId);if(!round)throw new GameError(409,'Start the question first.');if(!Number.isInteger(body.index)||body.index!==round.round_index){const old=this.one('SELECT * FROM rounds WHERE run_id=? AND round_index=?',runId,body.index??-1);if(old?.outcome&&old.submission_id===body.requestId)return this.view(r);throw new GameError(409,'This answer belongs to a different question. Refresh your dive.');}if(round.outcome)return this.view(r);if(typeof body.requestId!=='string'||body.requestId.length<8||body.requestId.length>100)throw new GameError(400,'A submission reference is required.');if(typeof body.answer!=='string'||body.answer.length>120)throw new GameError(400,'Answers must be 120 characters or fewer.');if(received<round.reading_until)throw new GameError(409,'The reading period has not finished.');const timedOut=round.deadline!==null&&received>round.deadline+250;const requestedTimeout=body.timeout===true;if(requestedTimeout&&round.deadline!==null&&received<=round.deadline+250)throw new GameError(409,'The answer period has not finished.');if(requestedTimeout&&round.deadline===null)throw new GameError(400,'Practice has no timeout.');let confirmed:string|undefined;if(!timedOut&&!requestedTimeout&&!matchAnswer(JSON.parse(r.snapshot)[round.round_index],body.answer)){const suggestion=suggestAnswer(JSON.parse(r.snapshot)[round.round_index],body.answer);if(suggestion&&body.confirmAnswer===suggestion.canonical)confirmed=suggestion.canonical;else if(suggestion)return {...this.view(r),suggestion:{canonical:suggestion.canonical,submitted:body.answer}};else return {...this.view(r),feedback:'That answer is not in the accepted list. Try another answer; the timer keeps running.'};}this.commit(r,round,body.answer,timedOut||requestedTimeout?'timeout':'answer',body.requestId,received,confirmed);return this.view(r);});}
 state(runId:string,session:string):RunView{return transaction(this.db,()=>this.view(this.owned(runId,session)));}
 view(r:Row):RunView{const current=this.reconcile(r);const rows=this.all('SELECT * FROM rounds WHERE run_id=? ORDER BY round_index',r.id);const outcomes:Outcome[]=rows.filter(v=>v.outcome).map(v=>JSON.parse(v.outcome));const total=outcomes.reduce((n,o)=>n+o.points,0);const latest=rows.at(-1);const index=latest?.round_index??0;const stage=Math.floor(index/7);const stageTotal=outcomes.filter(v=>Math.floor(v.index/7)===stage).reduce((n,o)=>n+o.points,0);const v:RunView={id:r.id,difficulty:r.difficulty??'mixed',topics:JSON.parse(r.categories),scoringVersion:r.scoring_version??'editorial-v1',mode:r.mode,relaxed:!!r.relaxed,state:r.complete?'complete':latest?.outcome?'result':latest?phase(this.clock(),latest.reading_until,latest.deadline)==='reading'?'reading':'answering':'result',serverNow:this.clock(),readingUntil:latest?.reading_until??null,deadline:latest?.deadline??null,round:index,total,depth:total*10,stageDepth:stageTotal*10,stage:stage+1,answered:outcomes.length,cycled:!!r.cycled};const participant=this.one('SELECT challenge_id FROM participants WHERE run_id=?',r.id);if(participant)v.challengeId=participant.challenge_id;if(latest){const p:Prompt=JSON.parse(r.snapshot)[index];v.prompt={id:p.id,version:p.version,category:p.category,text:p.text,notes:p.qualificationNotes};if(latest.outcome)v.outcome=JSON.parse(latest.outcome);}if(r.complete){const scoring=this.scoring(r.id);v.recap=outcomes.map(o=>{const p:Prompt=JSON.parse(r.snapshot)[o.index];return {...o,examples:p.answers.filter(a=>a.canonical!==o.canonical).slice(0,3).map(a=>`${a.canonical} · ${scoring[a.tier]} points`)};});}return v;}
 endEndless(runId:string,session:string){return transaction(this.db,()=>{const r=this.owned(runId,session);if(r.mode!=='endless')throw new GameError(400,'Only Endless dives can finish early.');const round=this.reconcile(r);if(round&&!round.outcome)throw new GameError(409,'Finish the active question before ending the dive.');this.finish(runId);return this.view({...r,complete:1});});}
 nickname(value:unknown){if(value===undefined||value==='')return 'Guest diver';if(typeof value!=='string'||value.length>24||/[\p{C}]/u.test(value))throw new GameError(400,'Use a nickname of 1–24 visible characters.');return value.trim()||'Guest diver';}
 challenge(cid:string):Row{const c=this.one('SELECT * FROM challenges WHERE id=?',cid);if(!c)throw new GameError(404,'We couldn’t find this challenge. Check the link or start a new dive.');if(c.expires<this.clock())throw new GameError(410,'This challenge has expired after 30 days. Start a fresh challenge.');return c;}
 createChallenge(session:string,body:Row):string{return transaction(this.db,()=>{const nickname=this.nickname(body.nickname);let runId:string;let snapshot:Prompt[];if(body.runId){const r=this.owned(body.runId,session);if(!r.complete||r.mode!=='solo'||r.relaxed)throw new GameError(400,'Only a completed timed seven-question solo dive can be shared as a challenge.');const existing=this.one('SELECT challenge_id FROM participants WHERE run_id=?',r.id);if(existing)return existing.challenge_id;runId=r.id;snapshot=JSON.parse(r.snapshot);}else{runId=this.newRun(session,'challenge',false,this.categories(body.categories),[],undefined,this.difficulty(body.difficulty));snapshot=JSON.parse(this.one('SELECT snapshot FROM runs WHERE id=?',runId)!.snapshot);}const cid=id();const now=this.clock();this.write('INSERT INTO challenges VALUES(?,?,?,?,?,?)',cid,now,now+30*86400000,this.one('SELECT scoring_version FROM runs WHERE id=?',runId)!.scoring_version,JSON.stringify({difficulty:this.one('SELECT difficulty FROM runs WHERE id=?',runId)!.difficulty,topics:JSON.parse(this.one('SELECT categories FROM runs WHERE id=?',runId)!.categories),scoringVersion:this.one('SELECT scoring_version FROM runs WHERE id=?',runId)!.scoring_version,readingMs:this.readingMs,answerMs:this.answerMs,toleranceMs:250,points:{...POINTS}}),JSON.stringify(snapshot));const completed=this.one('SELECT complete FROM runs WHERE id=?',runId)!.complete;this.write('INSERT INTO participants VALUES(?,?,?,?,?,?,?)',cid,'creator',session,nickname,runId,now,completed?now:null);return cid;});}
 summary(cid:string,session:string){const c=this.challenge(cid);const players=this.all('SELECT role,nickname,run_id,completed,session_id FROM participants WHERE challenge_id=? ORDER BY role',cid);const own=players.find(p=>p.session_id===session);const result:Row={id:cid,creator:players.find(p=>p.role==='creator')!.nickname,expires:c.expires,rules:JSON.parse(c.rules),players:players.map(p=>({role:p.role,nickname:p.nickname,complete:!!p.completed})),full:players.length===2,ownRole:own?.role,runId:own?.run_id};if(own){const view=this.state(own.run_id,session);result.runId=own.run_id;if(view.state==='complete'){const fresh=this.all('SELECT * FROM participants WHERE challenge_id=?',cid);result.results=fresh.map(p=>{if(!p.completed)return {nickname:p.nickname,role:p.role,pending:true};const r=this.one('SELECT * FROM runs WHERE id=?',p.run_id)!;const v=this.view(r);return {nickname:p.nickname,role:p.role,total:v.total,depth:v.depth,recap:v.recap};});}}return result;}
 claim(cid:string,session:string,nickname:unknown):string{return transaction(this.db,()=>{const c=this.challenge(cid);const own=this.one('SELECT run_id FROM participants WHERE challenge_id=? AND session_id=?',cid,session);if(own)return own.run_id;if(this.one('SELECT run_id FROM participants WHERE challenge_id=? AND role=?',cid,'friend'))throw new GameError(409,'This challenge already has two players. Start a separate game.');const name=this.nickname(nickname);const runId=this.newRun(session,'challenge',false,JSON.parse(c.rules).topics??[...new Set(JSON.parse(c.snapshot).map((p:Prompt)=>p.category))],[],JSON.parse(c.snapshot),JSON.parse(c.rules).difficulty??'mixed',c.scoring_version);this.write('INSERT INTO participants VALUES(?,?,?,?,?,?,?)',cid,'friend',session,name,runId,this.clock(),null);return runId;});}
 rematch(cid:string,session:string,nickname:unknown){this.challenge(cid);if(!this.one('SELECT run_id FROM participants WHERE challenge_id=? AND session_id=?',cid,session))throw new GameError(403,'Only a participant can create this rematch.');return this.createChallenge(session,{nickname});}
 report(session:string,body:Row){if(typeof body.runId!=='string'||!Number.isInteger(body.index))throw new GameError(400,'A completed question is required.');const r=this.owned(body.runId,session);const round=this.one('SELECT * FROM rounds WHERE run_id=? AND round_index=?',r.id,body.index);const prompt:Prompt|undefined=JSON.parse(r.snapshot)[body.index];const rejected=round&&prompt&&typeof body.answer==='string'&&body.answer.trim()&&body.answer.length<=120&&!matchAnswer(prompt,body.answer);if(!round?.outcome&&!rejected)throw new GameError(400,'Submit an unmatched answer first.');const o=round.outcome?JSON.parse(round.outcome):{promptId:prompt!.id,promptVersion:prompt!.version,submitted:body.answer};const explanation=typeof body.explanation==='string'?body.explanation.trim():'';if(explanation.length>1000)throw new GameError(400,'Keep the explanation under 1,000 characters.');this.write('INSERT INTO missing_reports VALUES(?,?,?,?,?,?,?)',id(),session,o.promptId,o.promptVersion,o.submitted,explanation,this.clock());}
}
