// Original learning notes for the one editorial Hidden gem in every prompt.
export const gemNotes:Record<string,string>={
 'africa':'São Tomé and Príncipe is an African island country in the Gulf of Guinea.',
 'asia':'Timor-Leste occupies the eastern part of Timor and nearby islands; the UN M49 scheme places it in South-eastern Asia.',
 'europe':'San Marino is a European microstate surrounded by Italy.',
 'americas':'Saint Kitts and Nevis is a two-island Caribbean federation and a UN member state.',
 'oceania':'Kiribati is an island country spread across Pacific atolls; the UN classifies it in Oceania.',
 'mediterranean':'Bosnia and Herzegovina reaches the Adriatic at Neum, giving it a Mediterranean coastline.',
 'landlocked':'Lesotho has no ocean coastline and is surrounded entirely by South Africa.',
 'us-states':'Wyoming is one of the 50 states; its capital is Cheyenne.',
 'elements':'Meitnerium, symbol Mt, is a synthetic element named for physicist Lise Meitner.',
 'one-letter-elements':'Yttrium uses the one-letter chemical symbol Y. Its name comes from Ytterby in Sweden.',
 'noble-gases':'Oganesson, symbol Og, occupies group 18, even though its predicted properties differ from the familiar noble gases.',
 'si-units':'The katal is the named SI unit of catalytic activity: one mole per second.',
 'constellations':'Reticulum is an IAU constellation in the southern sky; its name refers to a reticle.',
 'planets':'Makemake is one of the five IAU-recognised dwarf planets and lies in the Kuiper Belt.',
 'penguins':'Northern rockhopper penguins breed in the Tristan da Cunha island group, a UK Overseas Territory.',
 'british-birds':'The chough is a red-billed member of the crow family, associated in Britain with coastal cliffs.',
 'garden-plants':'Kniphofia is the red hot poker genus, known for tall flower spikes.',
 'tree-genera':'Metasequoia is the dawn redwood genus, a deciduous conifer grown in British gardens.',
 'pasta':'Garganelli are small ridged pasta tubes, traditionally rolled from squares of dough.',
 'herbs':'Asafoetida is a pungent resin used as a seasoning; it is also known as hing.',
 'citrus':'Sudachi is a small Japanese citrus used for its aromatic juice.',
 'breads':'A bialy is a bread roll with a depressed centre, traditionally filled with onion.',
 'cheese':'Valençay is a French goat’s cheese known for its truncated pyramid shape.',
 'greek-letters':'Xi is the Greek letter written Ξ or ξ. It is one of the standard 24 letters.',
 'nato-alphabet':'Juliett is the official NATO/ICAO spelling word for J; the final double t helps pronunciation across languages.',
 'irregular-past':'Sought is the simple past of seek, rather than a form ending in -ed.',
 'romance-languages':'Dalmatian was a Romance language spoken on the Adriatic coast; it is now extinct.',
 'shakespeare':'The Two Noble Kinsmen was written collaboratively by Shakespeare and John Fletcher and appears in the RSC play list.',
 'austen':'Northanger Abbey is one of Austen’s six completed novels and plays with the conventions of Gothic fiction.',
 'bond-films':'On Her Majesty’s Secret Service is the 1969 Eon Bond film starring George Lazenby.',
 'pixar-features':'The Good Dinosaur is Pixar’s 2015 feature about Arlo, a young dinosaur.',
 'instrument':'A nyckelharpa is a bowed string instrument with keys, associated especially with Sweden.',
 'greek-gods':'Melinoe is a Greek divine figure associated with ghosts in an Orphic hymn.',
 'roman-gods':'Portunus was a Roman god associated with ports, doors and harbours.',
 'chess-pieces':'The knight moves in an L-shaped pattern and can jump over other pieces.',
 'olympic-paris':'Breaking appeared on the Olympic programme at Paris 2024.',
 'athletics-events':'Paris 2024 included a mixed-team marathon race walk relay, replacing the former 50 km walk.',
 'world-cup-winners':'Uruguay won the men’s World Cup in 1930 and 1950.',
 'eu-2024':'Malta joined the European Union in 2004 and remained one of its 27 members at the question’s fixed date.',
 'nato-2024':'Luxembourg was one of NATO’s founding members in 1949.',
 'state-capitals':'Montpelier is the state capital of Vermont.',
 'english-counties':'Rutland is a ceremonial county of England as well as a unitary authority area.',
 'canada-divisions':'Nunavut is a Canadian territory, created in 1999 from part of the Northwest Territories.',
 'australia-divisions':'The Australian Capital Territory contains Canberra and is one of the two mainland territories accepted here.',
 'african-capitals':'Gitega is Burundi’s political capital; Bujumbura remains its economic centre.',
 'asian-capitals':'Sri Jayawardenepura Kotte is Sri Lanka’s legislative capital, while Colombo also serves important government functions.',
 'european-capitals':'Andorra la Vella is the capital of Andorra.',
 'med-islands':'Samothrace is a Greek island in the northern Aegean Sea.',
 'moons':'Kerberos is a small natural moon of the dwarf planet Pluto.',
 'moonwalkers':'Harrison Schmitt walked on the Moon during Apollo 17 and was the first professional scientist to do so.',
 'physics-laureates':'Isidor Rabi received the 1944 physics prize for his resonance method of recording magnetic properties of atomic nuclei.',
 'chemical-acids':'Gluconic acid is the carboxylic acid formed by oxidation of glucose’s aldehyde group.',
 'minerals':'Staurolite is a mineral known for characteristic cross-shaped twins.',
 'si-prefixes':'Quecto is the SI prefix for 10 to the power of −30, adopted in 2022.',
 'amino-acids':'Tryptophan is one of the standard protein-building amino acids; its three-letter abbreviation is Trp.',
 'human-bones':'The pisiform is a small carpal bone on the little-finger side of the wrist.',
 'human-muscles':'Palmaris longus is a forearm muscle whose long tendon is absent in some people.',
 'cloud-genera':'Cirrocumulus is one of the ten WMO cloud genera, generally seen as small high-level cloud elements.',
 'british-mammals':'The barbastelle is a British bat with broad ears that meet across its forehead.',
 'sharks':'The angular roughshark is a shark species with a distinctive angular body profile and tall dorsal fins.',
 'cetaceans':'The hourglass dolphin is a Southern Ocean cetacean with contrasting pale flank markings.',
 'british-butterflies':'The Lulworth skipper is a butterfly associated in Britain with the Dorset coast.',
 'uk-wildflowers':'Tormentil is a small yellow-flowered plant whose flowers usually have four petals.',
 'birds-of-prey':'The bearded vulture is also known as the lammergeier and is especially associated with feeding on bones.',
 'crocodilians':'The smooth-fronted caiman is a small South American crocodilian in the genus Paleosuchus.',
 'snake-species':'The elephant trunk snake is an aquatic snake with loose, wrinkled skin.',
 'seaweeds':'Sea spaghetti is the edible brown alga Himanthalia elongata, with long strap-like reproductive fronds.',
 'primates':'The emperor tamarin is a small South American monkey known for its long white moustache.',
 'vegetables':'Scorzonera, often called black salsify, is grown for its edible root.',
 'fruits':'Medlars are traditionally eaten after bletting, a softening process after harvest.',
 'legumes':'Bambara groundnut is an edible African legume whose pods develop underground.',
 'edible-seeds':'Candlenuts are used cooked in some South-east Asian cuisines; naming them here is not advice to eat them raw.',
 'grains':'Fonio is a small-grained West African cereal.',
 'mushrooms':'Black trumpet is the culinary name used for dark funnel-shaped mushrooms also called horn of plenty.',
 'soups':'Cullen skink is a Scottish soup traditionally made with smoked haddock, potatoes and onions.',
 'sauces':'Nantua sauce is a French sauce associated with crayfish, often based on béchamel.',
 'japanese-food':'Chawanmushi is a savoury Japanese steamed egg custard.',
 'indian-food':'Baingan bharta is an aubergine dish in which the aubergine is roasted and mashed.',
 'italian-dishes':'Bagna cauda is a warm Piedmontese anchovy-and-garlic dip, served with vegetables.',
 'french-pastry':'A sacristain is a twisted puff-pastry item, often made with almonds.',
 'cakes':'Dobos torte is a Hungarian layered sponge cake with chocolate buttercream and a caramel top.',
 'pancakes':'Baghrir is a North African pancake known for its many small holes.',
 'british-puddings':'Sussex pond pudding traditionally encloses a whole lemon with butter and sugar in a suet pastry.',
 'prepositions':'Owing to is a multi-word preposition expressing a cause.',
 'conjunctions':'Lest introduces a clause describing something to avoid or prevent.',
 'germanic-languages':'Norn was a North Germanic language formerly spoken in Orkney and Shetland.',
 'slavic-languages':'Kashubian is a West Slavic language spoken in northern Poland.',
 'indo-aryan':'Kalasha is an Indo-Aryan language spoken in northern Pakistan.',
 'punctuation':'An interrobang combines the functions of a question mark and an exclamation mark.',
 'rhetorical-devices':'Hendiadys expresses a single idea through two terms joined by and.',
 'literary-genres':'Picaresque fiction follows the episodic adventures of a roguish protagonist.',
 'classical-plurals':'Corpora is the Latin-derived plural of corpus.',
 'homophones':'Yew, you and ewe share a pronunciation in standard British English.',
 'composers':'Florence Price was an American composer whose works include symphonies and concertos.',
 'painters':'Hilma af Klint was a Swedish artist associated with early abstract painting.',
 'art-movements':'Vorticism was a British avant-garde movement associated with angular forms and modern industrial energy.',
 'dance-styles':'Sattriya is a classical Indian dance tradition associated with Assam.',
 'operas':'The Rake’s Progress is an opera by Igor Stravinsky, with a libretto by W. H. Auden and Chester Kallman.',
 'ballets':'Les Patineurs is a ballet choreographed by Frederick Ashton, depicting ice skaters.',
 'musicals':'Sunday in the Park with George is a stage musical by Stephen Sondheim and James Lapine.',
 'architecture':'Streamline Moderne is an architectural style associated with smooth curves and horizontal lines.',
 'london-museums':'Pitzhanger Manor in Ealing was the country home of architect John Soane and now houses a public gallery.',
 'sculptures':'Sleeping Muse is a sculptural work by Constantin Brâncuși, presenting a simplified resting head.',
 'spielberg':'The Sugarland Express was Spielberg’s 1974 theatrical feature about a couple on the run in Texas.',
 'hitchcock':'The Manxman is a 1929 silent feature directed by Hitchcock.',
 'nolan':'Following is Nolan’s first feature film, released in 1998.',
 'ghibli':'Ocean Waves is a feature-length television animation in the Ghibli catalogue, released in 1993.',
 'dickens':'Barnaby Rudge is Dickens’s historical novel set around the Gordon Riots.',
 'christie':'Death Comes as the End is a Christie mystery set in ancient Egypt.',
 'sherlock-stories':'The Musgrave Ritual is a Holmes short story involving an old family ritual and a hidden treasure.',
 'best-picture':'Marty won Best Picture at the Academy Awards ceremony held in 1956.',
 'dahl-books':'The Vicar of Nibbleswicke is a short Dahl book about a vicar whose words sometimes come out backwards.',
 'nfl-teams':'The Jacksonville Jaguars were an NFL franchise playing in the AFC South at the question’s fixed date.',
 'nba-teams':'The Indiana Pacers were one of the NBA’s 30 franchises in the 2024–25 season.',
 'mlb-teams':'The Seattle Mariners were an MLB franchise in the American League West in 2024.',
 'nhl-teams':'Utah Hockey Club was the temporary franchise name used in the NHL’s 2024–25 season.',
 'f1-champions':'Denny Hulme won the Formula One World Drivers’ Championship in 1967.',
 'f1-circuits':'Aintree hosted Formula One championship British Grands Prix in the 1950s and early 1960s.',
 'wimbledon-men':'Jan Kodeš won the Wimbledon men’s singles title in 1973.',
 'fa-cup-winners':'Clapham Rovers won the FA Cup in 1880.',
};
