import {chromium,expect,type Page} from '@playwright/test';
import {bank} from '../server/content';
import {createInterface} from 'node:readline';
const origin=process.argv[2];if(!origin?.startsWith('https://'))throw new Error('A verified HTTPS site URL is required.');
const browser=await chromium.launch({headless:true});const alice=await browser.newContext();const bob=await browser.newContext();const errors:string[]=[];
try{
const a=await alice.newPage();const b=await bob.newPage();for(const page of [a,b])page.on('pageerror',error=>errors.push(error.message));await a.goto(origin);await expect(a.getByRole('button',{name:'Play unlimited',exact:false})).toBeVisible();await a.getByRole('button',{name:'Challenge a friend',exact:false}).click();await a.getByLabel('Your nickname').fill('Test diver A');await a.getByRole('button',{name:'Create challenge',exact:true}).click();await expect(a.getByRole('heading',{name:'Test diver A’s dive'})).toBeVisible();const url=a.url();await a.getByRole('button',{name:'Play / resume challenge'}).click();
async function seven(page:Page){const ids:string[]=[];for(let index=0;index<7;index++){const input=page.getByLabel('Your answer',{exact:true});await expect(input).toBeEnabled({timeout:15000});const text=await page.locator('.question-panel h2').innerText();const prompt=bank.find(p=>p.text===text)!;ids.push(prompt.id);await input.fill(prompt.answers.find(a=>a.tier==='gem')!.canonical);await input.press('Enter');await expect(page.locator('.round-result,.recap')).toBeVisible({timeout:15000});if(index<6)await page.getByRole('button',{name:'Next prompt',exact:true}).click();}return ids;}
const first=await seven(a);console.log('Creator completed seven public questions.');await expect(a.locator('.recap-score')).toContainText('700');await a.getByRole('button',{name:'Compare results'}).click();await b.goto(url);await expect(b.getByRole('heading',{name:'Test diver A’s dive'})).toBeVisible();const spoilerCheck=await b.evaluate(async path=>(await fetch(path,{credentials:'same-origin'})).json(),new URL(url).pathname.replace('/challenge/','/api/challenges/'));if(spoilerCheck.results||spoilerCheck.snapshot)throw new Error('The invitation leaked hidden results.');await b.getByLabel('Your nickname').fill('Test diver B');await b.getByRole('button',{name:'Play challenge',exact:true}).click();const second=await seven(b);if(JSON.stringify(first)!==JSON.stringify(second))throw new Error('The challenge prompts differ.');await b.getByRole('button',{name:'Compare results'}).click();await expect(b.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();await a.getByRole('button',{name:'Refresh results'}).click();await expect(a.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();await b.reload();await expect(b.getByRole('heading',{name:'A draw — equal depths.'})).toBeVisible();await b.screenshot({path:'test-results/public-comparison.png',fullPage:true});await a.setViewportSize({width:360,height:800});await a.goto(origin);await expect(a.getByRole('button',{name:'Play unlimited',exact:false})).toBeVisible();if(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile layout overflows.');await a.screenshot({path:'test-results/public-mobile-home.png',fullPage:true});if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({status:'public-challenge-passed',origin,players:2,points:[700,700],matchingPrompts:7,mobileWidth:360,reload:true,pageErrors:0}));
console.log('Ready for persistence check after redeployment.');const lines=createInterface({input:process.stdin,output:process.stdout});await new Promise<void>(resolve=>lines.once('line',()=>resolve()));lines.close();for(const page of [a,b]){const response=await page.evaluate(async path=>{const response=await fetch(path,{credentials:'same-origin'});return {status:response.status,summary:await response.json()};},new URL(url).pathname.replace('/challenge/','/api/challenges/'));if(response.status!==200||response.summary.results?.length!==2||response.summary.results.some((r:any)=>r.total!==700))throw new Error('Persisted comparison was not retained after redeployment.');}console.log(JSON.stringify({status:'public-persistence-passed',origin,retainedPoints:[700,700]}));
await a.goto(origin);await a.getByRole('button',{name:'Play unlimited',exact:false}).click();if(await a.getByRole('button',{name:'Let’s dive',exact:true}).isVisible())await a.getByRole('button',{name:'Let’s dive',exact:true}).click();const input=a.getByLabel('Your answer',{exact:true});await expect(input).toBeEnabled({timeout:15000});const question=await a.locator('.question-panel h2').innerText();const prompt=bank.find(p=>p.text===question)!;await input.fill(prompt.answers.find(answer=>answer.tier==='gem')!.canonical);await input.press('Enter');await expect(a.locator('.round-result')).toContainText('+100',{timeout:15000});console.log(JSON.stringify({status:'public-new-save-passed',origin,points:100}));
}finally{await browser.close();}
