import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,connect} from './api';
import {Scene} from './Scene';
import {read,save,remove,storageAvailable} from './storage';
import {CATEGORIES,TIER_NAMES,type Settings,type RunView,type Outcome} from './shared/types';
import '@fontsource/barlow-condensed/latin-500.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/barlow-condensed/latin-700.css';
import '@fontsource/barlow-condensed/latin-800.css';
import '@fontsource/silkscreen/latin-400.css';
import './style.css';
const defaults:Settings={sound:false,reducedMotion:false,scanlines:true,relaxed:false,categories:[...CATEGORIES]};
const metres=(n:number)=>n.toLocaleString('en-GB')+' m';
type Page='home'|'game'|'settings'|'history'|'how'|'credits'|'challenge';
function App(){
 const [settings,setSettings]=useState(()=>read('settings',defaults));
 const [page,setPage]=useState<Page>(location.pathname.startsWith('/challenge/')?'challenge':'home');
 const [challengeId,setChallengeId]=useState(location.pathname.split('/challenge/')[1]??'');
 const [ready,setReady]=useState(false);const [bankSize,setBankSize]=useState(0);
 const [run,setRun]=useState<RunView|null>(null);const [challenge,setChallenge]=useState<any>(null);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [now,setNow]=useState(Date.now());
 const [draft,setDraft]=useState('');const [nickname,setNickname]=useState(()=>read('nickname','Guest diver'));
 const [modal,setModal]=useState<'challenge'|'report'|'instructions'|null>(null);const [report,setReport]=useState('');
 const [shareText,setShareText]=useState('');const [notice,setNotice]=useState('');
 const [history,setHistory]=useState<any[]>(()=>read('history',[]));
 const [resumeId,setResumeId]=useState<string|null>(()=>read('active',null));
 const [systemQuiet,setSystemQuiet]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);
 const firstMode=useRef<'solo'|'endless'>('solo');const instructionsSeen=useRef(read('instructionsSeen',false));const offset=useRef(0);const input=useRef<HTMLInputElement>(null);const retry=useRef<null|(()=>Promise<void>)>(null);
 const locked=useRef(false);const pending=useRef<any>(read('pending',null));const expiryFetch=useRef(false);const audio=useRef<AudioContext|null>(null);
 const quiet=settings.reducedMotion||systemQuiet;
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const listener=()=>setSystemQuiet(mq.matches);mq.addEventListener('change',listener);return()=>mq.removeEventListener('change',listener);},[]);
 useEffect(()=>{connect().then(data=>{setReady(true);setBankSize(data.content.prompts);setError('');}).catch(e=>{setError(e.message);retry.current=async()=>{const data=await connect();setReady(true);setBankSize(data.content.prompts);};});const tick=setInterval(()=>setNow(Date.now()+offset.current),100);const pop=()=>{const cid=location.pathname.split('/challenge/')[1];setChallengeId(cid??'');setPage(cid?'challenge':'home');};window.addEventListener('popstate',pop);return()=>{clearInterval(tick);window.removeEventListener('popstate',pop);};},[]);
 useEffect(()=>{save('settings',settings);},[settings]);
 async function task(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');retry.current=fn;try{await fn();retry.current=null;}catch(e){setError((e as Error).message);}finally{locked.current=false;setBusy(false);}}
 function navigate(p:Page,cid=''){setPage(p);setError('');setShareText('');setNotice('');if(p==='challenge'){setChallengeId(cid);historyPush(`/challenge/${cid}`);}else historyPush('/');}
 function historyPush(url:string){if(location.pathname!==url)window.history.pushState({},'',url);}
 function tone(){if(!settings.sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const oscillator=audio.current.createOscillator();const gain=audio.current.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(420,audio.current.currentTime);oscillator.frequency.exponentialRampToValueAtTime(160,audio.current.currentTime+.25);gain.gain.setValueAtTime(.045,audio.current.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.3);oscillator.connect(gain);gain.connect(audio.current.destination);oscillator.start();oscillator.stop(audio.current.currentTime+.3);}catch{/* Sound is optional. */}}
 function applyRun(v:RunView){offset.current=v.serverNow-Date.now();setNow(v.serverNow);setRun(v);setResumeId(v.state==='complete'?null:v.id);if(v.state==='complete'){remove('active');remove('pending');pending.current=null;const entries=read<any[]>('history',[]);if(!entries.some(h=>h.id===v.id)){const entry={id:v.id,date:new Date().toISOString(),mode:v.mode,relaxed:v.relaxed,total:v.total,depth:v.depth,answered:v.answered,recap:v.recap};const next=[entry,...entries].slice(0,50);save('history',next);setHistory(next);}}else save('active',v.id);if(v.state==='result'||v.state==='complete'){remove('pending');pending.current=null;}expiryFetch.current=false;}
 async function loadChallenge(){const c=await api(`/challenges/${challengeId}`);setChallenge(c);}
 useEffect(()=>{if(ready&&page==='challenge'&&challengeId){setChallenge(null);void task(loadChallenge);}},[ready,page,challengeId]);
 async function start(mode:'solo'|'endless'){if(!instructionsSeen.current){firstMode.current=mode;setModal('instructions');return;}await task(async()=>{const data=await api('/runs',{mode,relaxed:settings.relaxed,categories:settings.categories,recent:read('recent',[])});const v=await api(`/runs/${data.runId}/next`,{});applyRun(v);setDraft('');navigate('game');tone();});}
 async function resume(runId:string){await task(async()=>{let v=await api(`/runs/${runId}`);if(pending.current?.runId===runId&&v.state!=='complete'&&v.state!=='result')v=await api(`/runs/${runId}/submit`,pending.current.body);applyRun(v);setDraft('');navigate('game');});}
 async function next(){if(!run)return;await task(async()=>{const v=await api(`/runs/${run.id}/next`,{});applyRun(v);setDraft('');tone();});}
 const reading=!!run&&run.state==='reading'&&now<(run.readingUntil??0);
 const answering=!!run&&(run.state==='answering'||run.state==='reading')&&!reading;
 const timeLeft=run?.deadline===null?null:Math.max(0,Math.ceil(((run?.deadline??0)-now)/1000));
 const beforeDeadline=run?.deadline===null||now<=(run?.deadline??0);
 useEffect(()=>{if(answering&&!busy&&window.matchMedia('(pointer: fine)').matches)input.current?.focus();},[answering,run?.round]);
 useEffect(()=>{if(run?.prompt){const recent=read<string[]>('recent',[]);if(recent.at(-1)!==run.prompt.id)save('recent',[...recent,run.prompt.id].slice(-bankSize));}},[run?.prompt?.id,bankSize]);
 useEffect(()=>{if(!run||!answering||run.deadline===null||now<=run.deadline+350||busy||expiryFetch.current||error)return;expiryFetch.current=true;void task(async()=>{applyRun(await api(`/runs/${run.id}`));setDraft('');});},[now,run,answering,busy,error]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&run&&run.state!=='complete'&&!locked.current)void task(async()=>applyRun(await api(`/runs/${run.id}`)));};document.addEventListener('visibilitychange',refresh);return()=>document.removeEventListener('visibilitychange',refresh);},[run]);
 async function submit(){if(!run||!answering||!beforeDeadline||locked.current)return;const body={index:run.round,answer:draft,requestId:crypto.randomUUID()};pending.current={runId:run.id,body};save('pending',pending.current);await task(async()=>{applyRun(await api(`/runs/${run.id}/submit`,body));setDraft('');tone();});}
 async function finish(){if(run)await task(async()=>applyRun(await api(`/runs/${run.id}/finish`,{})));}
 async function createChallenge(){await task(async()=>{const body={nickname,categories:settings.categories,runId:page==='game'&&run?.state==='complete'&&run.mode==='solo'&&!run.relaxed?run.id:undefined};const c=await api('/challenges',body);save('nickname',nickname);setModal(null);setChallenge(null);navigate('challenge',c.id);});}
 async function playChallenge(){await task(async()=>{let runId=challenge.runId;if(!runId){const claim=await api(`/challenges/${challengeId}/claim`,{nickname});runId=claim.runId;save('nickname',nickname);}let v=await api(`/runs/${runId}`);if(!v.prompt&&v.state!=='complete')v=await api(`/runs/${runId}/next`,{});applyRun(v);setDraft('');navigate('game');});}
 async function share(text:string){setShareText(text);if(navigator.share){try{await navigator.share({title:'Deep Trivia',text});setNotice('Shared.');return;}catch(e){if((e as Error).name==='AbortError')return;}}try{await navigator.clipboard.writeText(text);setNotice('Copied to clipboard.');}catch{setNotice('Select the text below and copy it to share.');}}
 function resultText(v:RunView){return `Deep Trivia · ${v.mode==='endless'?'Endless dive':v.relaxed?'Untimed practice':'Seven-question dive'} · ${v.total}${v.mode==='endless'?'':'/700'} points · ${metres(v.depth)} descent · ${v.answered} questions. Play at ${location.origin}`;}
 const surface=page!=='game'||!run;const sceneDepth=surface?0:run.stageDepth;
 return <div data-depth={sceneDepth>=500?'deep':'surface'} className={`app ${quiet?'reduced-motion':''} ${settings.scanlines?'scanlines':''}`}>
  <Scene depth={sceneDepth} quiet={quiet}/>
  <header className="topbar"><button className="wordmark" onClick={()=>navigate('home')} aria-label="Deep Trivia home">DEEP<span>TRIVIA</span><small>AN OCEAN OF ANSWERS</small></button><div className="header-actions"><button className="icon-button" aria-label={settings.sound?'Mute sound':'Enable sound'} title={settings.sound?'Mute sound':'Enable sound'} onClick={()=>{setSettings({...settings,sound:!settings.sound});if(!settings.sound){audio.current??=new AudioContext();void audio.current.resume();}}}>{settings.sound?'♫':'♪'}<span>{settings.sound?'ON':'OFF'}</span></button><button className="icon-button" aria-label="Settings" onClick={()=>navigate('settings')}>⚙<span>SETTINGS</span></button></div></header>
  <main className={`main ${page==='home'?'home-main':''}`}>
  {error&&<div className="error-panel" role="alert"><p>{error}</p><div className="button-row"><button onClick={()=>{const again=retry.current;if(again)void task(again);}} disabled={busy}>Retry</button><button className="secondary" onClick={()=>navigate('home')}>Return to surface</button></div></div>}
  {notice&&!shareText&&<p className="notice" role="status">{notice}</p>}
  {!storageAvailable&&<p className="storage-warning" role="status">This browser cannot save local preferences or history. Keep this tab open; shared challenge results are still saved on the server.</p>}
  {page==='home'&&<section className="home-content">
   <div className="eyebrow"><span className="tiny-wave">≈</span> OPEN-ANSWER OCEAN TRIVIA</div>
   <h1>How deep does<br/>your <em>knowledge</em> go?</h1>
   <p className="home-intro">One question. Any valid answer.<br/>The rarer your discovery, the deeper you dive.</p>
   <div className="home-actions"><button className="primary big-button" disabled={!ready||busy} onClick={()=>void start('solo')}><span>Play unlimited</span><small>7 QUESTIONS · 25 SECONDS EACH</small></button><div className="split-actions"><button className="secondary" disabled={!ready||busy} onClick={()=>void start('endless')}>Endless dive <small>KEEP EXPLORING</small></button><button className="pink" disabled={!ready||busy} onClick={()=>setModal('challenge')}>Challenge a friend <small>SAME QUESTIONS. YOUR OWN PACE.</small></button></div>{resumeId&&<button className="text-button" disabled={!ready||busy} onClick={()=>void resume(resumeId)}>Resume your saved dive</button>}</div>
   <div className="home-details"><span>∞ FREE DIVES</span><span>NO ACCOUNT NEEDED</span><span>RARE ANSWERS WIN</span></div>
   <div className="home-secondary"><button className="text-button" onClick={()=>navigate('how')}>How to play</button><span>·</span><button className="text-button" onClick={()=>navigate('history')}>Your dive log</button></div>
   {settings.relaxed&&<p className="muted">Untimed practice is enabled for solo dives.</p>}
  </section>}
  {page==='game'&&run&&<section className="game-content">
   <div className="hud"><div><span>{run.mode==='endless'?'STAGE DEPTH':'DEPTH'}</span><strong>{metres(run.stageDepth)}</strong></div><div className="hud-middle"><span>{run.mode==='endless'?`STAGE ${run.stage}`:run.mode==='challenge'?'FRIEND CHALLENGE':run.relaxed?'UNTIMED PRACTICE':'UNLIMITED DIVE'}</span><strong>{run.state==='complete'?'DIVE COMPLETE':`${run.round%7+1} / 7`}</strong></div><div><span>{run.mode==='endless'?'SESSION SCORE':'SCORE'}</span><strong>{run.total}<small> pts</small></strong></div></div>
   {run.mode==='endless'&&<div className="endless-stats"><span>{run.answered} answered</span><span>{metres(run.depth)} total descent</span><span>{run.answered?(run.total/run.answered).toFixed(1):'0'} average</span></div>}
   {run.state!=='complete'&&run.prompt&&<>
    <div className="round-dots" aria-label={`Question ${run.round%7+1} of 7`}>{Array.from({length:7},(_,i)=><i key={i} className={i<run.round%7?'done':i===run.round%7?'current':''}/>)}</div>
    <div className="question-panel panel"><div className="question-heading"><span className="eyebrow">{run.prompt.category}</span><span className="zone-tag">{sceneDepth<500?'SURFACE':sceneDepth<1500?'TWILIGHT':sceneDepth<3500?'MIDNIGHT':sceneDepth<5500?'ABYSS':'TRENCH'}</span></div><h2>{run.prompt.text}</h2><p className="qualification">{run.prompt.notes}</p>
     {(run.state==='reading'||run.state==='answering')&&<><div className="timer" role="timer" aria-label={reading?'Reading period':timeLeft===null?'Untimed practice':`${timeLeft} seconds remaining`}><span>{reading?'TAKE A MOMENT TO READ':timeLeft===null?'UNTIMED PRACTICE':'TIME TO ANSWER'}</span><strong>{reading?`${Math.max(1,Math.ceil(((run.readingUntil??0)-now)/1000))}s`:timeLeft===null?'∞':`${timeLeft}s`}</strong></div><div className={`timer-track ${timeLeft!==null&&timeLeft<=5&&!reading?'urgent':''}`}><div style={{width:`${reading||timeLeft===null?100:Math.max(0,Math.min(100,((run.deadline??0)-now)/((run.deadline??0)-(run.readingUntil??0))*100))}%`}}/></div><form onSubmit={e=>{e.preventDefault();void submit();}}><label htmlFor="answer">Your answer</label><input id="answer" ref={input} placeholder={reading?'Get ready to dive…':'Something that fits…'} autoComplete="off" autoCorrect="off" spellCheck={false} maxLength={120} value={draft} disabled={reading||busy||!beforeDeadline} onChange={e=>setDraft(e.target.value)}/><button className="primary submit" type="submit" disabled={reading||busy||!beforeDeadline}>{busy?'Saving your answer…':reading?'Reading…':'Submit answer'}</button></form><p className="round-note">One committed answer. Editorial rarity rewards unusual discoveries.</p><div className="sr-only" aria-live="polite">{reading?'Read the question.':answering?'Answer period started.': ''}{!reading&&timeLeft===10?'Ten seconds remaining.':!reading&&timeLeft===5?'Five seconds remaining.':''}</div></>}
     {run.state==='result'&&run.outcome&&<><Result o={run.outcome}/>{run.outcome.status==='invalid'&&<button className="text-button" onClick={()=>{setReport('');setModal('report');}}>Report a missing answer</button>}<button className="primary next-button" onClick={()=>void next()} disabled={busy}>{run.mode==='endless'&&run.answered%7===0?'Continue diving': 'Next prompt'}</button>{run.mode==='endless'&&<button className="text-button" disabled={busy} onClick={()=>void finish()}>Finish dive{run.answered%7===0?' · Stage checkpoint':''}</button>}</>}
    </div>
    {run.cycled&&<p className="muted repeat-note">You’ve explored the eligible question bank. Questions may repeat.</p>}
   </>}
   {run.state==='complete'&&<div className="recap panel"><div className="eyebrow">{run.relaxed?'PRACTICE COMPLETE':'BACK FROM THE DEEP'}</div><h2>{run.total>=500?'What a discovery.':run.total>=200?'A brilliant little dive.':'There’s always more to discover.'}</h2><div className="recap-score"><strong>{run.total}<small>{run.mode==='endless'?' points':' / 700'}</small></strong><span>{metres(run.depth)}{run.mode==='endless'?' total descent':' deep'}</span></div><DepthGraph outcomes={run.recap??[]}/><Recap outcomes={run.recap??[]}/><div className="button-row"><button className="primary" onClick={()=>void start(run.mode==='endless'?'endless':'solo')} disabled={busy}>Play again</button>{run.mode==='solo'&&!run.relaxed&&<button className="pink" onClick={()=>setModal('challenge')}>Challenge a friend</button>}{run.challengeId&&<button className="pink" onClick={()=>navigate('challenge',run.challengeId)}>Compare results</button>}<button className="secondary" onClick={()=>void share(resultText(run))}>Share result</button></div><ShareFallback text={shareText} notice={notice}/>{run.relaxed&&<p className="muted">Untimed practice is excluded from timed personal records.</p>}</div>}
  </section>}
  {page==='challenge'&&<section className="panel challenge-panel"><div className="eyebrow">ASYNC FRIEND CHALLENGE</div>{challenge?<>
   <h1>{challenge.creator}’s dive</h1><p>Same seven questions. Same editorial scoring. Play when it suits you, then compare your discoveries.</p><div className="challenge-rules"><span>7 QUESTIONS</span><span>25 SECONDS EACH</span><span>700 POSSIBLE POINTS</span></div><p className="muted">Expires {new Date(challenge.expires).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}. Each answer begins after a three-second reading period.</p>
   {challenge.ownRole==='creator'&&<div className="invite-box"><h3>Invite your friend</h3><p>Anyone with this link can claim the single friend slot. Keep this browser’s cookies to return as yourself.</p><button className="pink" onClick={()=>void share(challenge.url??`${location.origin}/challenge/${challengeId}`)}>Copy / share invite</button><ShareFallback text={shareText} notice={notice}/></div>}
   {challenge.results?<><Comparison results={challenge.results}/><div className="button-row"><button className="primary" disabled={busy} onClick={()=>void task(loadChallenge)}>Refresh results</button><button className="pink" disabled={busy} onClick={()=>void task(async()=>{const c=await api(`/challenges/${challengeId}/rematch`,{nickname});setChallenge(null);navigate('challenge',c.id);})}>Rematch</button><button className="secondary" onClick={()=>void start('solo')}>Play unlimited</button></div></>:challenge.full&&!challenge.ownRole?<><h2>This challenge already has two players.</h2><p>You can start your own free dive or make a fresh challenge.</p><button className="primary" onClick={()=>void start('solo')}>Play unlimited</button></>:<><p className="privacy-note">Answers and scores stay hidden until you finish. This is a friendly competition: players may have seen a question before. Outside research cannot be prevented.</p>{!challenge.ownRole&&<Nickname value={nickname} onChange={setNickname}/>}<button className="primary big-button" disabled={busy} onClick={()=>void playChallenge()}>{challenge.ownRole?'Play / resume challenge':'Play challenge'}</button><p className="muted">{challenge.players.map((p:any)=>`${p.nickname}: ${p.complete?'finished':'not finished'}`).join(' · ')}</p></>}
   </>:!error?<p role="status">Loading your challenge…</p>:null}</section>}
  {page==='settings'&&<section className="panel settings-panel"><div className="eyebrow">MAKE YOURSELF AT HOME</div><h1>Dive settings</h1>{([['sound','Sound','Original, gentle result tones. Off by default.'],['reducedMotion','Reduced motion','Keep the ocean still and update depth immediately.'],['scanlines','Subtle scanlines','A little retro texture around the controls.'],['relaxed','Untimed solo practice','Learn at your own pace. Friend challenges remain timed.']] as const).map(([key,label,desc])=><label className="setting-row" key={key}><div><strong>{label}</strong><span>{desc}</span></div><input type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}<fieldset><legend>Solo categories</legend><p className="muted">Select enough categories for seven distinct prompts. Challenges from a completed dive use that dive’s exact questions.</p><div className="category-grid">{CATEGORIES.map(c=><label key={c}><input type="checkbox" checked={settings.categories.includes(c)} onChange={e=>setSettings({...settings,categories:e.target.checked?[...settings.categories,c]:settings.categories.filter(v=>v!==c)})}/>{c}</label>)}</div></fieldset><div className="button-row"><button className="primary" onClick={()=>navigate('home')}>Back to surface</button><button className="secondary" onClick={()=>navigate('credits')}>Content & credits</button></div></section>}
  {page==='how'&&<section className="panel prose"><div className="eyebrow">YOUR FIRST DIVE</div><h1>Unusual answers.<br/>Deeper discoveries.</h1><p>Each question asks you to name one example of a category. Take three seconds to read, then use your 25 seconds to type a single answer. Press Enter or Submit to commit it.</p><p>Answers match a curated list, including aliases and accented spellings. An invalid answer or blank timeout scores zero and ends that question. An unfinished draft is never submitted automatically.</p><div className="tier-list">{Object.entries(TIER_NAMES).map(([key,name],i)=><div key={key}><span>{name}</span><strong>{[10,30,60,85,100][i]} pts</strong></div>)}</div><p>These are editorial rarity tiers, not measured popularity. Every point takes you ten metres deeper. Seven Hidden gems earn 700 points and reach 7,000 metres.</p><p>Unlimited gives you fresh seven-question dives. Endless continues across seven-question ocean stages, with a cumulative session total. You can pause between questions; an active timer keeps running in menus and background tabs.</p><p>Friend challenges are asynchronous. Share an invitation, play the same questions separately, and compare after finishing. Equal totals draw. Invitations last 30 days.</p><p>The bank is finite and may miss a valid answer. You can report one for review. Questions repeat after you explore the selected bank.</p><button className="primary" onClick={()=>navigate('home')}>Ready to dive</button></section>}
  {page==='history'&&<section className="panel"><div className="eyebrow">THIS BROWSER’S EXPLORATIONS</div><h1>Your dive log</h1><p className="muted">The latest 50 completed dives are stored in this browser. Challenge results live on their shared link.</p>{history.length===0?<p>No completed dives yet. The ocean is waiting.</p>:<><p className="personal-best">Timed seven-question best: <strong>{Math.max(0,...history.filter(h=>!h.relaxed&&h.mode!=='endless').map(h=>h.total))} / 700</strong></p><div className="history-list">{history.map(h=><div key={h.id}><div><strong>{h.mode==='endless'?'Endless':h.relaxed?'Untimed practice':h.mode==='challenge'?'Challenge':'Unlimited'}</strong><small>{new Date(h.date).toLocaleDateString('en-GB')} · {h.answered} questions</small></div><span>{h.total} pts<br/><small>{metres(h.depth)}</small></span></div>)}</div><button className="secondary" onClick={()=>{remove('history');setHistory([]);}}>Clear local history</button></>}<button className="text-button" onClick={()=>navigate('home')}>Back to surface</button></section>}
  {page==='credits'&&<section className="panel prose"><div className="eyebrow">CURATED, WITH CURIOSITY</div><h1>Content & credits</h1><p>{bankSize} original prompts are currently available across eight categories. The answer lists are finite; report a missing answer from its result screen.</p><p>Factual references include the <a href="https://www.un.org/about-us/member-states" target="_blank" rel="noreferrer">United Nations</a>, <a href="https://periodic-table.rsc.org/" target="_blank" rel="noreferrer">Royal Society of Chemistry</a>, <a href="https://www.rspb.org.uk/birds-and-wildlife" target="_blank" rel="noreferrer">RSPB</a>, <a href="https://www.rhs.org.uk/" target="_blank" rel="noreferrer">RHS</a>, <a href="https://www.rsc.org.uk/shakespeares-plays" target="_blank" rel="noreferrer">Royal Shakespeare Company</a>, and official film and sport organisations. Full prompt references and review notes are supplied with the project.</p><p>All question wording, explanations, geometric ocean artwork and synthesised sounds are original. The locally bundled Barlow Condensed and Silkscreen fonts is licensed under the SIL Open Font License; body text uses system fonts. No Krillion question bank, artwork, branding or sounds are used.</p><p>Ocean bands are stylised scenery, not a scientific depth model. No real player-popularity percentages are used.</p><button className="primary" onClick={()=>navigate('home')}>Back to surface</button></section>}
  </main><footer><span>DEEP TRIVIA</span><span>TAKE A BREATH. MAKE A DISCOVERY.</span><button className="text-button" onClick={()=>navigate('credits')}>Content & credits</button></footer>
  <div className="sr-only" aria-live="polite">{busy?'Saving or loading your dive.':notice}</div>
  {modal&&<Modal close={()=>setModal(null)}><h2 id="modal-title">{modal==='instructions'?'Before you dive':modal==='challenge'?'Dive with a friend':'Report a missing answer'}</h2>{error&&<p role="alert" className="modal-error">{error}</p>}{modal==='instructions'?<><p>Read each question for three seconds, then take 25 seconds to name one valid example. Press Enter or Submit to commit one answer.</p><p>Editorial rarity scores 10–100 points. Every point takes you ten metres deeper. An unmatched answer or blank timeout scores zero; unfinished drafts are never submitted automatically.</p><p>Choose Next prompt when you’re ready. Timers continue in menus and background tabs. You can enable untimed solo practice in Settings.</p><button className="primary big-button" onClick={()=>{instructionsSeen.current=true;save('instructionsSeen',true);setModal(null);void start(firstMode.current);}}>Let’s dive</button></>:modal==='challenge'?<><p>Play the same seven questions separately and compare after finishing. No account needed.</p><Nickname value={nickname} onChange={setNickname}/><button className="pink big-button" disabled={!ready||busy} onClick={()=>void createChallenge()}>{busy?'Creating…':'Create challenge'}</button></>:<><p>Your submitted answer and question version will be saved for content review. Reports do not change this score.</p><label htmlFor="report">Why does your answer fit? (optional)</label><textarea id="report" maxLength={1000} value={report} onChange={e=>setReport(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>void task(async()=>{await api('/reports',{runId:run?.id,index:run?.round,explanation:report});setModal(null);setNotice('Report saved. Thank you.');})}>Save report</button></>}</Modal>}
 </div>;
}
function Nickname({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="nickname"><label htmlFor="nickname">Your nickname</label><input id="nickname" value={value} maxLength={24} onChange={e=>onChange(e.target.value)} autoComplete="nickname"/></div>;}
function Result({o}:{o:Outcome}){return <div className={`round-result ${o.status}`} role="status"><div className="result-heading"><span>{o.status==='accepted'?TIER_NAMES[o.tier!]:o.status==='timeout'?'Time’s up':'Unmatched answer'}</span><strong>+{o.points}<small> pts</small></strong></div><h3>{o.canonical??(o.submitted||'No answer committed')}</h3>{o.canonical&&o.canonical.toLowerCase()!==o.submitted.toLowerCase()&&<p className="muted">You typed: {o.submitted}</p>}<p>{o.explanation}</p><span className="depth-gain">{o.points*10} metres deeper</span></div>;}
function Recap({outcomes}:{outcomes:Outcome[]}){return <div className="recap-list">{outcomes.map(o=><details key={o.index}><summary><span className={`recap-number ${o.status}`}>{o.index+1}</span><div><strong>{o.canonical??(o.submitted||'Timed out')}</strong><span>{o.tier?TIER_NAMES[o.tier]:o.status==='timeout'?'Timeout':'Unmatched'}</span></div><b>{o.points} pts</b></summary><div className="recap-detail"><p><strong>{o.prompt}</strong></p><p>You entered: {o.submitted||'(blank timeout)'}</p><p>{o.explanation}</p>{o.examples&&<p>Other discoveries: {o.examples.join(' · ')}</p>}</div></details>)}</div>;}
function Comparison({results}:{results:any[]}){const done=results.filter(p=>!p.pending);const winner=done.length===2?(done[0].total===done[1].total?'A draw — equal depths.':`${done[0].total>done[1].total?done[0].nickname:done[1].nickname} dives deepest!`):'Waiting for your friend';return <div className="comparison"><h2>{winner}</h2><div className="comparison-totals">{results.map(p=><div key={p.role}><span>{p.nickname}</span><strong>{p.pending?'…':`${p.total} pts`}</strong><small>{p.pending?'Not finished':metres(p.depth)}</small></div>)}</div>{done.length===2&&<div className="comparison-rounds">{done[0].recap.map((o:Outcome,i:number)=><div key={i}><h3>{i+1}. {o.prompt}</h3><div className="comparison-pair">{done.map(p=>{const a=p.recap[i];return <div key={p.role}><small>{p.nickname}</small><strong>{a.canonical??(a.submitted||'Timed out')}</strong><span>{a.points} pts · {a.tier?TIER_NAMES[a.tier as keyof typeof TIER_NAMES]:a.status}</span></div>;})}</div></div>)}</div>}</div>;}
function DepthGraph({outcomes}:{outcomes:Outcome[]}){let total=0;const points=['0,0',...outcomes.map((o,i)=>{total+=o.points;return `${(i+1)/Math.max(1,outcomes.length)*600},${total/Math.max(700,outcomes.reduce((n,x)=>n+x.points,0))*80}`;})].join(' ');return <div className="depth-graph"><svg viewBox="0 -5 600 100" role="img" aria-label={`Cumulative descent: ${total*10} metres across ${outcomes.length} questions`}><path d="M0 0H600M0 40H600M0 80H600" stroke="#ffffff15"/><polyline points={points} fill="none" stroke="#59e1f4" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><span>YOUR DESCENT</span></div>;}
function ShareFallback({text,notice}:{text:string;notice:string}){return text?<div className="share-fallback"><p role="status">{notice||'Select or copy your sharing text:'}</p><label className="sr-only" htmlFor="sharing-text">Sharing text</label><textarea id="sharing-text" readOnly value={text} onFocus={e=>e.target.select()}/></div>:null;}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous?.focus();},[]);return <dialog aria-labelledby="modal-title" ref={ref} onCancel={e=>{e.preventDefault();close();}} className="panel modal"><button className="modal-close secondary" aria-label="Close dialog" onClick={close}>×</button>{children}</dialog>;}
createRoot(document.getElementById('root')!).render(<App/>);
